export type Difficulty = 'baby' | 'easy' | 'medium' | 'hard' | 'professional';

export interface Achievement {
	id: string,
	difficulty: Difficulty,
	title: string,
	condition: string,
	category: string,
	counter?: string,
	value?: number,
	manual?: true,
}

const reactionAchievementFactory = (title: string, reaction: string, reactionThreshold: number): Achievement => {
	let difficulty: Difficulty = 'medium';
	if (reactionThreshold <= 3) {
		difficulty = 'medium';
	} else if (reactionThreshold <= 5) {
		difficulty = 'hard';
	} else {
		difficulty = 'professional';
	}
	return {
		id: `reaction-${reaction}-${reactionThreshold}`,
		difficulty,
		title,
		condition: `1つのメッセージに対し${reactionThreshold}人以上から:${reaction}:リアクションをもらう`,
		category: 'reactions',
		counter: `reaction-${reaction}-${reactionThreshold}`,
		value: 1,
	};
};

const achievements: Achievement[] = [
	{
		id: 'chat',
		difficulty: 'baby',
		title: 'はじめまして!',
		condition: 'パブリックなチャンネルで初めて発言する',
		category: 'basic',
		counter: 'chats',
		value: 1,
	},
	{
		id: 'chat-10times',
		difficulty: 'easy',
		title: 'ｽｯｺｺｺ',
		condition: 'パブリックなチャンネルで10回以上発言する',
		category: 'basic',
		counter: 'chats',
		value: 10,
	},
	{
		id: 'chat-1000times',
		difficulty: 'hard',
		title: '話の種',
		condition: 'パブリックなチャンネルで1000回以上発言する',
		category: 'basic',
		counter: 'chats',
		value: 1000,
	},
	{
		id: 'chat-10000times',
		difficulty: 'hard',
		title: '竿の先',
		condition: 'パブリックなチャンネルで10000回以上発言する',
		category: 'basic',
		counter: 'chats',
		value: 10000,
	},
	{
		id: 'chat-20000times',
		difficulty: 'hard',
		title: '禍の門',
		condition: 'パブリックなチャンネルで20000回以上発言する',
		category: 'basic',
		counter: 'chats',
		value: 20000,
	},
	{
		id: 'chat-30000times',
		difficulty: 'hard',
		title: '喋喋喃喃',
		condition: 'パブリックなチャンネルで30000回以上発言する',
		category: 'basic',
		counter: 'chats',
		value: 30000,
	},
	{
		id: 'chat-50000times',
		difficulty: 'hard',
		title: '縷縷綿綿',
		condition: 'パブリックなチャンネルで50000回以上発言する',
		category: 'basic',
		counter: 'chats',
		value: 50000,
	},
	{
		id: 'chat-100000times',
		difficulty: 'hard',
		title: '立て板に水',
		condition: 'パブリックなチャンネルで100000回以上発言する',
		category: 'basic',
		counter: 'chats',
		value: 100000,
	},
	{
		id: 'chat-10days',
		difficulty: 'medium',
		title: '常連',
		condition: 'パブリックなチャンネルでのべ10日間発言する',
		category: 'basic',
		counter: 'chatDays',
		value: 10,
	},
	{
		id: 'chat-100days',
		difficulty: 'hard',
		title: 'いつものメンバー',
		condition: 'パブリックなチャンネルでのべ100日間発言する',
		category: 'basic',
		counter: 'chatDays',
		value: 100,
	},
	{
		id: 'chat-1000days',
		difficulty: 'professional',
		title: 'TSGの主',
		condition: 'パブリックなチャンネルでのべ1000日間発言する',
		category: 'basic',
		counter: 'chatDays',
		value: 1000,
	},
	{
		id: 'chat-10000days',
		difficulty: 'professional',
		title: '歴史の語り部',
		condition: 'パブリックなチャンネルでのべ10000日間発言する',
		category: 'basic',
		counter: 'chatDays',
		value: 10000,
	},

	// reactions
	reactionAchievementFactory('支離滅裂', 'ha', 5),
	reactionAchievementFactory('デビルマン', 'wakari', 5),
	reactionAchievementFactory('ジャガーマン', 'koresuki', 5),
	reactionAchievementFactory('あーここすき', 'koresuki', 10),
	reactionAchievementFactory('もっとすいみんぶそく', 'koresuki', 15),
	reactionAchievementFactory('伝説のアイドル', 'koresuki', 20),
	reactionAchievementFactory('今日からやの付く自由業', 'yakuza', 5),
	reactionAchievementFactory('狂気の沙汰ほど面白い...！', 'shoki-ka', 5),
	reactionAchievementFactory('聞いてよアカネちゃん！', 'seyana', 5),
	reactionAchievementFactory('TSGMELTDOWN', 'chian-ga-nai', 5),
	reactionAchievementFactory('コンテキスト不一致', 'context', 5),
	reactionAchievementFactory('みんな違ってみんなプロ', 'pro', 5),
	reactionAchievementFactory('仕事の流儀', 'pro', 10),
	reactionAchievementFactory('プロプログラマー', 'pro', 15),
	reactionAchievementFactory('あなたにとって、sandboxとは何ですか？', 'pro', 20),
	reactionAchievementFactory('君はお肉が好き？', 'shirimetsuretsu', 5),
	reactionAchievementFactory('理性ある生き物', 'riaru', 5),
	reactionAchievementFactory('地位は人をつくる', 'erai', 5),
	reactionAchievementFactory('台風の目', 'guchol', 5),
	reactionAchievementFactory('お前はナンなんだ', 'ナンやねん-ナンなので', 5),
	reactionAchievementFactory('ドジでよく泣くキツネの子', 'hideo54', 5),
	reactionAchievementFactory('海藻を買いそう', 'kombu', 5),
	reactionAchievementFactory('鳥さんが鳴いとるやんけ', 'hototogisu', 5),
	reactionAchievementFactory('ねこは今日もあなたの後ろでおじぎしている', 'ojigineko', 5),
	reactionAchievementFactory('ねぇ、あなたは何のフレンズ？', 'serval', 5),
	reactionAchievementFactory('415 Unsupported PizzaNeco Type', 'pizzacat83', 5),
	reactionAchievementFactory('胡麻は2粒でもピリリと黒い', 'kurgm', 5),
	reactionAchievementFactory('巨人の肩の上で', 'genius', 5),
	reactionAchievementFactory('明日まで考えておいてください。そしたら何か、見えてくるはずです', 'kachi', 5),
	reactionAchievementFactory('永劫の闇を司るTSGer', 'yami', 5),
	reactionAchievementFactory('丑三つ DOKI DOKI', 'korosuzo', 5),
	reactionAchievementFactory('プログラミング風実績解放ゲーム', 'mnemo', 5),
	reactionAchievementFactory('tadaより嬉しいものはない', 'tada', 5),
	reactionAchievementFactory('山田くん座布団一枚持ってって', 'no-zabuton', 5),
	reactionAchievementFactory('LooksGoodToTSG', 'yosasou', 5),
	reactionAchievementFactory('私がプロだ', 'hakatashi-pro', 5),
	reactionAchievementFactory('この町で出会えた奇跡', 'shamiko', 5),
	reactionAchievementFactory('ずっと輝いてる未来はここにある', 'freshpeach', 5),
	reactionAchievementFactory('誰がなんと言おうと優上のはずなんだ', '95', 5),
	reactionAchievementFactory('今日も一日がんばるぞい！', 'zoi', 5),
	reactionAchievementFactory('河童のラッパー今日もご立派', 'rhyme', 5),
	reactionAchievementFactory('よろしくおねがいします_メモ', 'scp-040-jp', 5),
	reactionAchievementFactory('ゆえにTSGは世界中を統べる団体である', 'contradiction', 5),
	reactionAchievementFactory('嘘つきは実績の始まり', 'sorehauso', 5),
	reactionAchievementFactory('正直者が実績を見る', 'sorehasou', 5),
	reactionAchievementFactory('た͜͜͏̘̣͔͙͎͎̘̜̫̗͍͚͓͜͜͏̘̣͔͙͎͎す͜͜͏̘̣͔͙͎͎ơ̟̤̖̗͖͇̍͋̀͆̓́͞͡け̜ͪ̅̍̅͂͊て', 'kowa', 5),
	reactionAchievementFactory('す単落々堂我', '0ten', 5),
	reactionAchievementFactory('指差し確認ヨシ！', 'genbaneko', 5),
	reactionAchievementFactory('どうして夜中に起きてるんですか？', 'denwaneko', 5),
	reactionAchievementFactory('TSGの松尾芭蕉', 'ikku', 5),
	reactionAchievementFactory('なんだ猫か...', 'nya-n', 5),
	reactionAchievementFactory('理由もなくチヤホヤされたい', 'yumemiriamu', 5),
	reactionAchievementFactory('チョロいなオタク！', 'yumemiriamu', 10),
	reactionAchievementFactory('あまり強い言葉を使うなよ', 'jimei', 5),
	reactionAchievementFactory('平和より戦争を始める方がはるかに易しい', 'kaishaku-chigai', 5),
	reactionAchievementFactory('自堕落アイドルへの道', 'kurotorianzu', 5),
	reactionAchievementFactory('pwnpwnpain', 'pwn', 5),
	reactionAchievementFactory('1.667レアコイル', 'coil', 5),
	reactionAchievementFactory('レアコイル', 'coil', 3),
	reactionAchievementFactory('君はかわいいですね', 'nanachi', 5),
	reactionAchievementFactory('お前は冷蔵庫！', 'reizoukotte', 5),
	reactionAchievementFactory('バナナのナナチがゆらゆら', 'banananachi', 5),
	reactionAchievementFactory('なんだしなんだしTSG', 'agc', 5),
	reactionAchievementFactory('新感覚実績アクションゲェーム！', 'american-battle-dome', 5),
	reactionAchievementFactory('桜よくね？', 'crocodile-with-100-remaining-days-of-life', 5),
	reactionAchievementFactory('俺が好きなこのキャラをお前が好きなはずはない', 'doutan-kyohi', 5),
	reactionAchievementFactory('実績 is You', 'baba', 5),
	reactionAchievementFactory('実績になるから散歩したい', 'jimmy-sanpo', 5),
	reactionAchievementFactory('ハッ！取り乱してしまいましたわ！', 'kusowayo', 5),
	reactionAchievementFactory('学歴コンプ', 'kyoudai-kanjo', 5),
	reactionAchievementFactory('実績を解除したいという煩悩', '108', 5),
	reactionAchievementFactory('自身が転んでもおかしいお年頃', 'nameraka_rotating_rolling_on_the_floor_laughing', 5),
	reactionAchievementFactory('インドのナンごをたべるんご', 'appingorou', 5),
	reactionAchievementFactory('なんだ猫...か...?', 'neko', 5),
	reactionAchievementFactory('解除それ以上', 'joyman-takagi', 5),
	reactionAchievementFactory('ここにいられる奇跡に感謝', 'undakeno', 5),
	reactionAchievementFactory('実績取るやん', 'mounttoru', 5),
	reactionAchievementFactory('テンパイ即リー、速攻にゃ速攻ーっ！', 'ichihime-zekkocho', 5),
	reactionAchievementFactory('起床時間乱数生成器', 'lifestyle-breaking', 5),
	reactionAchievementFactory('エミネムさんが実績について教えてくれるそうです', 'eminem', 5),
	reactionAchievementFactory('生みの楽しみ', 'tukutte', 5),
	reactionAchievementFactory('Understand 理解した', 'understand-1', 5),
	reactionAchievementFactory('Understand 完全に理解した', 'understand-10', 5),
	reactionAchievementFactory('無知の知', 'understand-', 5),
	reactionAchievementFactory('今言うなは考えるにゃしである', 'んー', 5),
	reactionAchievementFactory('最低の思考は混乱の中から生まれる', 'blob-panic', 5),
	reactionAchievementFactory('「突然ですが、僕はTSGが大好きだ。」', 'kaibunsho', 5),
	reactionAchievementFactory('時には詩人のように', 'iihanashi', 5),
	reactionAchievementFactory('領収書が捨てられる', 'yatta-', 5),
	reactionAchievementFactory('まだまだ上がある', '100', 5),
	reactionAchievementFactory('くぅーっ‼️', 'oxtu', 5),
	reactionAchievementFactory('男達が後ろから撃たれるチャンネル', 'otaku', 5),
	reactionAchievementFactory('「友ある者は、敗残者ではない」', 'waiwai', 5),
	reactionAchievementFactory('非エモーショナル', 'hie-', 5),
	reactionAchievementFactory('お気の毒に...', 'pensive', 5),

	{
		id: 'reaction-koresuki-5-first-reaction-1',
		difficulty: 'medium',
		title: '目利き',
		condition: '5人以上から:koresuki:でリアクションされたメッセージに最初にリアクションする',
		category: 'reactions',
		counter: 'reaction-koresuki-5-first-reaction',
		value: 1,
	},
	{
		id: 'reaction-koresuki-5-first-reaction-10',
		difficulty: 'hard',
		title: 'これすき職人',
		condition: '「5人以上から:koresuki:でリアクションされたメッセージに最初にリアクションする」を10回達成する',
		category: 'reactions',
		counter: 'reaction-koresuki-5-first-reaction',
		value: 10,
	},
	{
		id: 'reaction-koresuki-5-first-reaction-100',
		difficulty: 'professional',
		title: 'これすき発掘王',
		condition: '「5人以上から:koresuki:でリアクションされたメッセージに最初にリアクションする」を100回達成する',
		category: 'reactions',
		counter: 'reaction-koresuki-5-first-reaction',
		value: 100,
	},
	{
		id: 'reaction-koresuki-5-first-reaction-1000',
		difficulty: 'professional',
		title: 'これすきの導き手',
		condition: '「5人以上から:koresuki:でリアクションされたメッセージに最初にリアクションする」を1000回達成する',
		category: 'reactions',
		counter: 'reaction-koresuki-5-first-reaction',
		value: 1000,
	},
	{
		id: 'reaction-koresuki-10-first-reaction-1',
		difficulty: 'hard',
		title: '流行の火付け役',
		condition: '10人以上から:koresuki:でリアクションされたメッセージに最初にリアクションする',
		category: 'reactions',
		counter: 'reaction-koresuki-10-first-reaction',
		value: 1,
	},
	{
		id: 'reaction-20-reactions-first-reaction-1',
		difficulty: 'professional',
		title: 'アジテーション',
		condition: '20人以上から同じリアクションがつけられたメッセージに、最初にそのリアクションをする',
		category: 'reactions',
		counter: 'reaction-20-reactions-first-reaction',
		value: 1,
	},
	{
		id: 'reaction-20-reactions-first-reaction-10',
		difficulty: 'professional',
		title: 'トレンドの作成者',
		condition: '「20人以上から同じリアクションがつけられたメッセージに、最初にそのリアクションをする」を10回達成する',
		category: 'reactions',
		counter: 'reaction-20-reactions-first-reaction',
		value: 10,
	},
	{
		id: 'reaction-ki-to-o-reactions-1',
		difficulty: 'easy',
		title: 'オマイラ',
		condition: '「き」で始まる他人のメッセージの先頭を「お」に置き換えた絵文字でリアクションをする',
		category: 'reactions',
		counter: 'reaction-ki-to-o-reactions',
		value: 1,
	},
	{
		id: 'reaction-ki-to-o-reactions-30',
		difficulty: 'medium',
		title: '恩赦',
		condition: '「き」で始まる他人のメッセージの先頭を「お」に置き換えた絵文字で30回リアクションする',
		category: 'reactions',
		counter: 'reaction-ki-to-o-reactions',
		value: 30,
	},
	{
		id: 'reaction-ki-to-o-reactions-500',
		difficulty: 'hard',
		title: '折り返し',
		condition: '「き」で始まる他人のメッセージの先頭を「お」に置き換えた絵文字で500回リアクションする',
		category: 'reactions',
		counter: 'reaction-ki-to-o-reactions',
		value: 500,
	},
	{
		id: 'reaction-ki-to-o-reactions-1000',
		difficulty: 'professional',
		title: '大銀杏',
		condition: '「き」で始まる他人のメッセージの先頭を「お」に置き換えた絵文字で1000回リアクションする',
		category: 'reactions',
		counter: 'reaction-ki-to-o-reactions',
		value: 1000,
	},
	{
		id: 'reaction-o-to-ki-reactions-1',
		difficulty: 'easy',
		title: 'きまいら',
		condition: '「お」で始まる他人のメッセージの先頭を「き」に置き換えた絵文字でリアクションをする',
		category: 'reactions',
		counter: 'reaction-o-to-ki-reactions',
		value: 1,
	},
	{
		id: 'reaction-o-to-ki-reactions-30',
		difficulty: 'medium',
		title: '金砂',
		condition: '「お」で始まる他人のメッセージの先頭を「き」に置き換えた絵文字で30回リアクションする',
		category: 'reactions',
		counter: 'reaction-o-to-ki-reactions',
		value: 30,
	},
	{
		id: 'reaction-o-to-ki-reactions-500',
		difficulty: 'hard',
		title: '切り返し',
		condition: '「お」で始まる他人のメッセージの先頭を「き」に置き換えた絵文字で500回リアクションする',
		category: 'reactions',
		counter: 'reaction-o-to-ki-reactions',
		value: 500,
	},
	{
		id: 'reaction-o-to-ki-reactions-1000',
		difficulty: 'professional',
		title: '紀尾井町',
		condition: '「お」で始まる他人のメッセージの先頭を「き」に置き換えた絵文字で1000回リアクションする',
		category: 'reactions',
		counter: 'reaction-o-to-ki-reactions',
		value: 1000,
	},
	{
		id: 'reaction-ki-to-o-reactions-emoji-types-5',
		difficulty: 'medium',
		title: '帰宅マニア',
		condition: '「「き」で始まる他人のメッセージの先頭を「お」に置き換えた絵文字でリアクションをする」を異なる5種類の絵文字で達成する',
		category: 'reactions',
		counter: 'reaction-ki-to-o-reactions-emoji-types',
		value: 5,
	},
	{
		id: 'reaction-ki-to-o-reactions-emoji-types-15',
		difficulty: 'hard',
		title: '帰省マニア',
		condition: '「「き」で始まる他人のメッセージの先頭を「お」に置き換えた絵文字でリアクションをする」を異なる15種類の絵文字で達成する',
		category: 'reactions',
		counter: 'reaction-ki-to-o-reactions-emoji-types',
		value: 15,
	},
	{
		id: 'reaction-ki-to-o-reactions-emoji-types-50',
		difficulty: 'professional',
		title: '帰国マニア',
		condition: '「「き」で始まる他人のメッセージの先頭を「お」に置き換えた絵文字でリアクションをする」を異なる50種類の絵文字で達成する',
		category: 'reactions',
		counter: 'reaction-ki-to-o-reactions-emoji-types',
		value: 50,
	},
	{
		id: 'reaction-o-to-ki-reactions-emoji-types-5',
		difficulty: 'medium',
		title: 'オタクマニア',
		condition: '「「お」で始まる他人のメッセージの先頭を「き」に置き換えた絵文字でリアクションをする」を異なる5種類の絵文字で達成する',
		category: 'reactions',
		counter: 'reaction-o-to-ki-reactions-emoji-types',
		value: 5,
	},
	{
		id: 'reaction-o-to-ki-reactions-emoji-types-15',
		difficulty: 'hard',
		title: 'オセイマニア',
		condition: '「「お」で始まる他人のメッセージの先頭を「き」に置き換えた絵文字でリアクションをする」を異なる15種類の絵文字で達成する',
		category: 'reactions',
		counter: 'reaction-o-to-ki-reactions-emoji-types',
		value: 15,
	},
	{
		id: 'reaction-o-to-ki-reactions-emoji-types-50',
		difficulty: 'professional',
		title: 'オコクマニア',
		condition: '「「お」で始まる他人のメッセージの先頭を「き」に置き換えた絵文字でリアクションをする」を異なる50種類の絵文字で達成する',
		category: 'reactions',
		counter: 'reaction-o-to-ki-reactions-emoji-types',
		value: 50,
	},
	{
		id: 'reaction-ki-to-o-reactions-first-1',
		difficulty: 'medium',
		title: 'オタク部1の俊足',
		condition: '「き」で始まる他人のメッセージの先頭を「お」に置き換えた絵文字で最初にリアクションをする',
		category: 'reactions',
		counter: 'reaction-ki-to-o-reactions-first',
		value: 1,
	},
	{
		id: 'reaction-ki-to-o-reactions-first-100',
		difficulty: 'hard',
		title: 'オタサンブラック',
		condition: '「き」で始まる他人のメッセージの先頭を「お」に置き換えた絵文字で最初に100回リアクションをする',
		category: 'reactions',
		counter: 'reaction-ki-to-o-reactions-first',
		value: 100,
	},
	{
		id: 'reaction-o-to-ki-reactions-first-1',
		difficulty: 'medium',
		title: '帰宅特有の早口',
		condition: '「お」で始まる他人のメッセージの先頭を「き」に置き換えた絵文字で最初にリアクションをする',
		category: 'reactions',
		counter: 'reaction-o-to-ki-reactions-first',
		value: 1,
	},
	{
		id: 'reaction-o-to-ki-reactions-first-100',
		difficulty: 'hard',
		title: 'キグリキャップ',
		condition: '「お」で始まる他人のメッセージの先頭を「き」に置き換えた絵文字で最初に100回リアクションをする',
		category: 'reactions',
		counter: 'reaction-o-to-ki-reactions-first',
		value: 100,
	},

	// sushi-bot

	{
		id: 'get-sushi',
		difficulty: 'baby',
		title: '玉子',
		condition: 'sushi-botから寿司をもらう',
		category: 'sushi-bot',
	},
	{
		id: 'get-multiple-sushi',
		difficulty: 'easy',
		title: 'マグロ',
		condition: 'sushi-botから一度に2個以上の寿司をもらう',
		category: 'sushi-bot',
	},
	{
		id: 'get-infinite-sushi',
		difficulty: 'easy',
		title: 'ハマチ',
		condition: 'sushi-botから一度に無限個の寿司をもらう',
		category: 'sushi-bot',
	},
	{
		id: 'wednesday-sushi',
		difficulty: 'medium',
		title: 'すしすしすいようび',
		condition: '水曜日にsushi-botから寿司をもらう',
		category: 'sushi-bot',
	},
	{
		id: 'freezing',
		difficulty: 'easy',
		title: 'フリージング',
		condition: 'sushi-botに凍結される',
		category: 'sushi-bot',
	},
	{
		id: 'freezing-master',
		difficulty: 'hard',
		title: '氷属性',
		condition: '週間凍結ランキングで1位を獲得する',
		category: 'sushi-bot',
	},
	{
		id: 'asa',
		difficulty: 'easy',
		title: '新しい朝が来た',
		condition: 'あさ宣言で正の得点を獲得する',
		category: 'sushi-bot',
	},
	{
		id: 'asa-over80',
		difficulty: 'medium',
		title: '生活リズムゲームノルマクリア',
		condition: 'あさ宣言で80点以上の得点を獲得する',
		category: 'sushi-bot',
	},
	{
		id: 'asa-master',
		difficulty: 'hard',
		title: '布団時代の終焉を告げる者',
		condition: '週間起床ランキングで単独1位を獲得する',
		category: 'sushi-bot',
	},
	{
		id: 'asa-week-720',
		difficulty: 'professional',
		title: '生活リズム・パーフェクトゲーム',
		condition: '週間起床ランキングで720点以上を獲得する',
		category: 'sushi-bot',
	},
	{
		id: 'asa-week-0',
		difficulty: 'hard',
		title: '生活リズム・完全敗北',
		condition: '週間起床ランキングで0点以下を獲得し、ランキングに掲載される',
		category: 'sushi-bot',
	},
	{
		id: 'asa-week-perfect',
		difficulty: 'professional',
		title: '生活リズム・オールパーフェクト',
		condition: '週間起床ランキングで満点を獲得する',
		category: 'sushi-bot',
	},
	{
		id: 'first-exercise',
		difficulty: 'easy',
		title: '一日一善体力づくり',
		condition: '運動する',
		category: 'sushi-bot',
	},
	{
		id: 'everyday-exercise-week',
		difficulty: 'hard',
		title: 'エクササイズ週間皆勤賞',
		condition: '週七日運動する',
		category: 'sushi-bot',
	},
	{
		id: 'exercise-30',
		difficulty: 'medium',
		title: '一月分の運動',
		condition: '30日運動する',
		category: 'sushi-bot',
		counter: 'exercise-cumulative',
		value: 30,
	},
	{
		id: 'exercise-60',
		difficulty: 'hard',
		title: '二月分の運動',
		condition: '60日運動する',
		category: 'sushi-bot',
		counter: 'exercise-cumulative',
		value: 60,
	},
	{
		id: 'exercise-100',
		difficulty: 'hard',
		title: 'チリも積もれば筋となる',
		condition: '100日運動する',
		category: 'sushi-bot',
		counter: 'exercise-cumulative',
		value: 100,
	},
	{
		id: 'exercise-180',
		difficulty: 'professional',
		title: 'エクササイズ・ハーフイヤー・セレブレーション',
		condition: '180日運動する',
		category: 'sushi-bot',
		counter: 'exercise-cumulative',
		value: 180,
	},
	{
		id: 'exercise-365',
		difficulty: 'professional',
		title: 'イチロー・スズキ',
		condition: '365日運動する',
		category: 'sushi-bot',
		counter: 'exercise-cumulative',
		value: 365,
	},

	// dajare

	{
		id: 'zabuton',
		difficulty: 'easy',
		title: 'だじゃれを言うのは誰じゃ',
		condition: 'dajareボットから:zabuton:をもらう',
		category: 'dajare',
	},
	{
		id: 'zabutons',
		difficulty: 'easy',
		title: 'タワーの上に登ったわー',
		condition: 'dajareボットから:zabutons:をもらう',
		category: 'dajare',
	},
	{
		id: 'flying-zabuton',
		difficulty: 'easy',
		title: '座布団がぶっ飛んだ',
		condition: 'dajareボットから:flying-zabuton:をもらう',
		category: 'dajare',
	},

	// pocky

	{
		id: 'pocky',
		difficulty: 'baby',
		title: 'はま寿司',
		condition: 'pockyに反応される',
		category: 'pocky',
	},
	{
		id: 'long-pocky',
		difficulty: 'medium',
		title: 'スーモ',
		condition: 'pockyから20文字以上の返答を得る',
		category: 'pocky',
	},
	{
		id: 'quine-pocky',
		difficulty: 'medium',
		title: 'やまびこやまびこ',
		condition: 'pockyに与えた文字列と同一の返答を得る。ただし一度言われたものは不可',
		category: 'pocky',
	},
	{
		id: 'self-pocky',
		difficulty: 'medium',
		title: 'エゴサーチ？',
		condition: 'Slackの表示名とpockyからの返答が一致する',
		category: 'pocky',
	},
	{
		id: 'long-quine-pocky',
		difficulty: 'professional',
		title: '(‘ω’)',
		condition: 'pockyに与えた文字列と同一の、20文字以上の返答を得る。ただし一度言われたものは不可',
		category: 'pocky',
	},
	{
		id: 'pocky-on-nov-11',
		difficulty: 'medium',
		title: '最後までチョコたっぷり',
		condition: '11月11日にpockyに反応される',
		category: 'pocky',
	},
	{
		id: 'pockygame-on-nov-11',
		difficulty: 'medium',
		title: 'Stick to fun!',
		condition: '11月11日にポッキーゲームに勝利する',
		category: 'pocky',
	},
	{
		id: 'pockygame-win-1',
		difficulty: 'easy',
		title: '堅焼きプレッツェル',
		condition: 'ポッキーゲームに1回勝利する',
		category: 'pocky',
		counter: 'pockygame-win',
		value: 1,
	},
	{
		id: 'pockygame-win-10',
		difficulty: 'medium',
		title: 'ラッキースティック',
		condition: 'ポッキーゲームに10回勝利する',
		category: 'pocky',
		counter: 'pockygame-win',
		value: 10,
	},
	{
		id: 'pockygame-win-100',
		difficulty: 'hard',
		title: 'フランダブルショコラ',
		condition: 'ポッキーゲームに100回勝利する',
		category: 'pocky',
		counter: 'pockygame-win',
		value: 100,
	},
	{
		id: 'pockygame-win-1000',
		difficulty: 'professional',
		title: 'MIKADO',
		condition: 'ポッキーゲームに1000回勝利する',
		category: 'pocky',
		counter: 'pockygame-win',
		value: 1000,
	},

	// tahoiya

	{
		id: 'tahoiya',
		difficulty: 'easy',
		title: '千里の道も一歩から',
		condition: 'たほいやに参加する',
		category: 'tahoiya',
	},
	{
		id: 'daily-tahoiya-theme',
		difficulty: 'medium',
		title: '大智は愚の如し',
		condition: 'デイリーたほいやにお題を登録する',
		category: 'tahoiya',
	},
	{
		id: 'tahoiya-over6',
		difficulty: 'medium',
		title: '坊主丸儲け',
		condition: 'たほいやで一度にプラス6点以上獲得する',
		category: 'tahoiya',
	},
	{
		id: 'tahoiya-over10',
		difficulty: 'hard',
		title: '一攫千金',
		condition: 'たほいやで一度にプラス10点以上獲得する',
		category: 'tahoiya',
	},
	{
		id: 'tahoiya-down10',
		difficulty: 'medium',
		title: '悪銭身につかず',
		condition: 'たほいやで前回より10点以上低い点数を獲得する',
		category: 'tahoiya',
	},
	{
		id: 'tahoiya-deceive',
		difficulty: 'medium',
		title: '笑中に刀あり',
		condition: 'たほいやで他の人をひっかける',
		category: 'tahoiya',
	},
	{
		id: 'tahoiya-deceive3',
		difficulty: 'hard',
		title: '麦飯で鯉を釣る',
		condition: 'たほいやで1度に3人以上をひっかける',
		category: 'tahoiya',
	},
	{
		id: 'tahoiya-5bet',
		difficulty: 'medium',
		title: '乾坤一擲',
		condition: 'たほいやで5枚BETする',
		category: 'tahoiya',
	},
	{
		id: 'tahoiya-singularity',
		difficulty: 'medium',
		title: 'シンギュラリティ',
		condition: 'たほいやでAIに振り込んでしまう',
		category: 'tahoiya',
	},
	{
		id: 'tahoiya-positive-coins-without-win',
		difficulty: 'hard',
		title: '負けるが勝ち',
		condition: 'たほいやで誤った選択肢にBETした上で正の得点を獲得する',
		category: 'tahoiya',
	},
	{
		id: 'tahoiya-deceive-each-other',
		difficulty: 'hard',
		title: '鷸蚌の争い',
		condition: 'たほいやでお互いの登録した意味に振り込み合う (BOTを除く)',
		category: 'tahoiya',
	},
	{
		id: 'tahoiya-wins-10',
		difficulty: 'hard',
		title: '勝てば官軍',
		condition: 'たほいやで延べ10勝する (BOT以外の参加者が3人以上の場合に限る)',
		category: 'tahoiya',
		counter: 'tahoiyaWin',
		value: 10,
	},
	{
		id: 'tahoiya-wins-100',
		difficulty: 'professional',
		title: '百戦殆うからず',
		condition: 'たほいやで延べ100勝する (BOT以外の参加者が3人以上の場合に限る)',
		category: 'tahoiya',
		counter: 'tahoiyaWin',
		value: 100,
	},
	{
		id: 'tahoiya-deceive-total7',
		difficulty: 'medium',
		title: '狐七化け、狸は八化け',
		condition: 'たほいやで延べ8人をひっかける',
		category: 'tahoiya',
		counter: 'tahoiyaDeceive',
		value: 8,
	},
	{
		id: 'tahoiya-deceive-total300',
		difficulty: 'professional',
		title: '三百代言',
		condition: 'たほいやで延べ300人をひっかける',
		category: 'tahoiya',
		counter: 'tahoiyaDeceive',
		value: 300,
	},
	{
		id: 'tahoiya-participate-10',
		difficulty: 'medium',
		title: '芸は道によって賢し',
		condition: 'たほいやに10回参加する (BOT以外の参加者が3人以上の場合に限る)',
		category: 'tahoiya',
		counter: 'tahoiyaParticipate',
		value: 10,
	},
	{
		id: 'tahoiya-participate-100',
		difficulty: 'hard',
		title: '松笠より年嵩',
		condition: 'たほいやに50回参加する (BOT以外の参加者が3人以上の場合に限る)',
		category: 'tahoiya',
		counter: 'tahoiyaParticipate',
		value: 50,
	},
	{
		id: 'tahoiya-participate-300',
		difficulty: 'professional',
		title: '海千山千',
		condition: 'たほいやに300回参加する (BOT以外の参加者が3人以上の場合に限る)',
		category: 'tahoiya',
		counter: 'tahoiyaParticipate',
		value: 300,
	},
	{
		id: 'tahoiya-firstplace',
		difficulty: 'hard',
		title: '歩く百科事典',
		condition: 'たほいやのランキングで1位になる',
		category: 'tahoiya',
	},

	// mahjong

	{
		id: 'mahjong',
		difficulty: 'easy',
		title: 'みっつずつ、みっつずつ⋯⋯',
		condition: '麻雀BOTの四麻モードで和了する',
		category: 'mahjong',
	},
	{
		id: 'mahjong-七対子',
		difficulty: 'medium',
		title: 'ふたつずつ、ふたつずつ⋯⋯',
		condition: '麻雀BOTの四麻モードで七対子を和了する',
		category: 'mahjong',
	},
	{
		id: 'mahjong-12000',
		difficulty: 'easy',
		title: 'ザンクを三回刻むより',
		condition: '麻雀BOTの四麻モードで満貫以上を和了する',
		category: 'mahjong',
	},
	{
		id: 'mahjong-24000',
		difficulty: 'medium',
		title: '来たぜぬるりと',
		condition: '麻雀BOTの四麻モードで倍満以上を和了する',
		category: 'mahjong',
	},
	{
		id: 'mahjong-36000',
		difficulty: 'hard',
		title: '御無礼',
		condition: '麻雀BOTの四麻モードで三倍満以上を和了する',
		category: 'mahjong',
	},
	{
		id: 'mahjong-48000',
		difficulty: 'professional',
		title: '麻雀って楽しいね！',
		condition: '麻雀BOTの四麻モードで役満を和了する',
		category: 'mahjong',
	},
	{
		id: 'mahjong-ikeda',
		difficulty: 'easy',
		title: '池田ァ！',
		condition: '麻雀BOTの四麻モードで七筒を切る',
		category: 'mahjong',
	},
	{
		id: 'mahjong-不聴立直',
		difficulty: 'medium',
		title: '後の三巡',
		condition: '麻雀BOTの四麻モードで不聴立直をする',
		category: 'mahjong',
	},
	{
		id: 'mahjong-ドラ8',
		difficulty: 'professional',
		title: 'ドラゴンロード',
		condition: '麻雀BOTの四麻モードでドラを8枚以上含む手で和了する',
		category: 'mahjong',
	},
	{
		id: 'mahjong-海底摸月',
		difficulty: 'hard',
		title: '片腹大激痛',
		condition: '麻雀BOTの四麻モードで海底摸月を和了する',
		category: 'mahjong',
	},
	{
		id: 'mahjong-西単騎',
		difficulty: 'hard',
		title: '単騎は西で待て',
		condition: '麻雀BOTの四麻モードで西の単騎待ちで和了する',
		category: 'mahjong',
	},
	{
		id: 'mahjong-一四索',
		difficulty: 'professional',
		title: '早い立直は一四索',
		condition: '麻雀BOTの四麻モードで、6巡以内に一四索の両面待ちで立直を行った上で和了する',
		category: 'mahjong',
	},
	{
		id: 'mahjong-invalid-kan',
		difficulty: 'easy',
		title: 'その嶺上取る必要なし',
		condition: '麻雀BOTでカンを試みる',
		category: 'mahjong',
	},
	{
		id: 'mahjong-chinitsu-quiz-answer-1',
		difficulty: 'easy',
		title: '立てて跳満',
		condition: 'チンイツクイズで1回正解する',
		category: 'mahjong',
		counter: 'mahjong-chinitsu-quiz-answer',
		value: 1,
	},
	{
		id: 'mahjong-chinitsu-quiz-answer-10',
		difficulty: 'medium',
		title: 'メンチンすぎて恐いの',
		condition: 'チンイツクイズで10回正解する',
		category: 'mahjong',
		counter: 'mahjong-chinitsu-quiz-answer',
		value: 10,
	},
	{
		id: 'mahjong-chinitsu-quiz-answer-100',
		difficulty: 'hard',
		title: 'メンチンの王',
		condition: 'チンイツクイズで100回正解する',
		category: 'mahjong',
		counter: 'mahjong-chinitsu-quiz-answer',
		value: 100,
	},
	{
		id: 'mahjong-chinitsu-quiz-answer-1000',
		difficulty: 'professional',
		title: 'メンチンのバビィ',
		condition: 'チンイツクイズで1000回正解する',
		category: 'mahjong',
		counter: 'mahjong-chinitsu-quiz-answer',
		value: 1000,
	},
	{
		id: 'mahjong-chinitsu-quiz-hard-answer-1',
		difficulty: 'medium',
		title: 'O(nlogn)の節約',
		condition: 'チンイツクイズhardで1回正解する',
		category: 'mahjong',
		counter: 'mahjong-chinitsu-quiz-hard-answer',
		value: 1,
	},
	{
		id: 'mahjong-chinitsu-quiz-hard-answer-15',
		difficulty: 'hard',
		title: 'Unsorted Bin Attack',
		condition: 'チンイツクイズhardで15回正解する',
		category: 'mahjong',
		counter: 'mahjong-chinitsu-quiz-hard-answer',
		value: 15,
	},
	{
		id: 'mahjong-chinitsu-quiz-hard-answer-200',
		difficulty: 'professional',
		title: '0.2秒で分かっちゃいますよ',
		condition: 'チンイツクイズhardで500回正解する',
		category: 'mahjong',
		counter: 'mahjong-chinitsu-quiz-hard-answer',
		value: 500,
	},
	{
		id: 'mahjong-chinitsu-quiz-noten-1',
		difficulty: 'easy',
		title: 'メンチンと風呂の湯は張っていたほうがいい',
		condition: 'チンイツクイズでノーテンで正解する',
		category: 'mahjong',
		counter: 'mahjong-chinitsu-quiz-noten',
		value: 1,
	},
	{
		id: 'mahjong-chinitsu-quiz-1men-1',
		difficulty: 'easy',
		title: '非効率',
		condition: 'チンイツクイズで1面張の問題に正解する',
		category: 'mahjong',
		counter: 'mahjong-chinitsu-quiz-1men',
		value: 1,
	},
	{
		id: 'mahjong-chinitsu-quiz-tamen-1',
		difficulty: 'easy',
		title: '麻雀わからないよ～',
		condition: 'チンイツクイズで5面張以上の問題に正解する',
		category: 'mahjong',
		counter: 'mahjong-chinitsu-quiz-tamen',
		value: 1,
	},
	{
		id: 'mahjong-chinitsu-quiz-9men-1',
		difficulty: 'professional',
		title: '天衣無縫',
		condition: 'チンイツクイズで9面張の問題に正解する',
		category: 'mahjong',
		counter: 'mahjong-chinitsu-quiz-9men',
		value: 1,
	},

	// shogi

	{
		id: 'shogi',
		difficulty: 'easy',
		title: '勝ち将棋鬼の如し',
		condition: '将棋BOTで勝利する',
		category: 'shogi',
	},
	{
		id: 'shogi-shortest',
		difficulty: 'medium',
		title: '長い詰みより短い必至',
		condition: '将棋BOTで最短勝利する',
		category: 'shogi',
	},
	{
		id: 'shogi-shortest-without-end',
		difficulty: 'hard',
		title: '長考に好手なし',
		condition: '将棋BOTで一発で最短勝利する (7手必勝以上に限る)',
		category: 'shogi',
	},
	{
		id: 'shogi-win-10',
		difficulty: 'hard',
		title: '碁で負けたら将棋で勝て',
		condition: '将棋BOTで10回最短勝利する (7手必勝以上に限る)',
		category: 'shogi',
		counter: 'shogiWin',
		value: 10,
	},
	{
		id: 'shogi-win-100',
		difficulty: 'professional',
		title: '月下の棋士',
		condition: '将棋BOTで100回最短勝利する (7手必勝以上に限る)',
		category: 'shogi',
		counter: 'shogiWin',
		value: 100,
	},
	{
		id: 'shogi-over11',
		difficulty: 'hard',
		title: '勝ち将棋を勝て',
		condition: '将棋BOTで11手必勝以上の盤面で最短勝利する',
		category: 'shogi',
	},
	{
		id: 'shogi-over19',
		difficulty: 'hard',
		title: '攻めるは守るなり',
		condition: '将棋BOTで19手必勝以上の盤面で最短勝利する',
		category: 'shogi',
	},
	{
		id: 'shogi-over19-without-end',
		difficulty: 'professional',
		title: '名人に定跡なし',
		condition: '将棋BOTで19手必勝以上の盤面で一発で最短勝利する',
		category: 'shogi',
	},
	{
		id: 'shogi-銀不成',
		difficulty: 'hard',
		title: '銀は不成に好手あり',
		condition: '将棋BOTで銀不成を含む手順で最短勝利する (7手必勝以上に限る)',
		category: 'shogi',
	},
	{
		id: 'shogi-自陣飛車',
		difficulty: 'hard',
		title: '自陣飛車に好手あり',
		condition: '将棋BOTで自陣への飛車打を含む手順で最短勝利する (7手必勝以上に限る)',
		category: 'shogi',
	},
	{
		id: 'shogi-自陣角',
		difficulty: 'hard',
		title: '遠見の角に好手あり',
		condition: '将棋BOTで自陣への角打を含む手順で最短勝利する (7手必勝以上に限る)',
		category: 'shogi',
	},
	{
		id: 'shogi-歩成',
		difficulty: 'medium',
		title: 'マムシのと金',
		condition: '将棋BOTで歩成を含む手順で最短勝利する (7手必勝以上に限る)',
		category: 'shogi',
	},
	{
		id: 'shogi-三桂',
		difficulty: 'hard',
		title: '三桂あって詰まぬことなし',
		condition: '将棋BOTで桂馬を3つ以上所持した初期盤面で最短勝利する (7手必勝以上に限る)',
		category: 'shogi',
	},
	{
		id: 'shogi-打ち歩詰め',
		difficulty: 'hard',
		title: '打ち歩詰めに詰みの余地あり',
		condition: '将棋BOTで打ち歩詰めで敗北する',
		category: 'shogi',
	},

	// prime

	{
		id: 'prime',
		difficulty: 'baby',
		title: 'ピタゴラス',
		condition: '素数大富豪で遊ぶ',
		category: 'prime',
	},
	{
		id: 'prime-clear',
		difficulty: 'medium',
		title: 'ディオファントス',
		condition: '素数大富豪をクリアする',
		category: 'prime',
	},
	{
		id: 'prime-fast-clear',
		difficulty: 'medium',
		title: 'レオンハルト・オイラー',
		condition: '素数大富豪を4ターン以内でクリアする',
		category: 'prime',
	},
	{
		id: 'prime-fast-clear-no-draw',
		difficulty: 'medium',
		title: 'カール・フリードリヒ・ガウス',
		condition: '素数大富豪をドローせずに4ターン以内でクリアする',
		category: 'prime',
	},
	{
		id: 'prime-fast-clear-no-draw-no-penalty',
		difficulty: 'hard',
		title: 'エヴァリスト・ガロア',
		condition: '素数大富豪をドローおよびペナルティ無しで4ターン以内でクリアする',
		category: 'prime',
	},
	{
		id: 'prime-composition-8',
		difficulty: 'medium',
		title: 'ジョゼフ＝ルイ・ラグランジュ',
		condition: '素数大富豪で合成数出しによって8枚以上を同時に捨てる',
		category: 'prime',
	},
	{
		id: 'prime-grothendieck',
		difficulty: 'medium',
		title: 'アレクサンドル・グロタンディーク',
		condition: '素数大富豪でグロタンカットを発生させる',
		category: 'prime',
	},
	{
		id: 'prime-ramanujan',
		difficulty: 'medium',
		title: 'シュリニヴァーサ・ラマヌジャン',
		condition: '素数大富豪でラマヌジャン革命を発生させる',
		category: 'prime',
	},
	{
		id: 'prime-mersenne',
		difficulty: 'medium',
		title: 'マラン・メルセンヌ',
		condition: '素数大富豪で3桁以上のメルセンヌ素数を捨てる',
		category: 'prime',
	},
	{
		id: 'prime-fermat',
		difficulty: 'medium',
		title: 'ピエール・ド・フェルマー',
		condition: '素数大富豪で3桁以上のフェルマー素数を捨てる',
		category: 'prime',
	},
	{
		id: 'prime-fibonacci',
		difficulty: 'medium',
		title: 'レオナルド・フィボナッチ',
		condition: '素数大富豪で3桁以上のフィボナッチ素数を捨てる',
		category: 'prime',
	},
	{
		id: 'prime-lucas',
		difficulty: 'medium',
		title: 'エドゥアール・リュカ',
		condition: '素数大富豪で3桁以上のリュカ素数を捨てる',
		category: 'prime',
	},
	{
		id: 'prime-wolstenholme',
		difficulty: 'medium',
		title: 'ジョセフ・ウォルステンホルム',
		condition: '素数大富豪で3桁以上のウォルステンホルム素数を捨てる',
		category: 'prime',
	},

	// voiperrobot

	{
		id: 'voiperrobot',
		difficulty: 'easy',
		title: 'はっつくパンツ',
		condition: 'ボイパーロボットで遊ぶ',
		category: 'voiperrobot',
	},
	{
		id: 'voiperrobot-battle',
		difficulty: 'easy',
		title: 'ひっつくパンツ',
		condition: 'ボイパーロボットバトルで遊ぶ',
		category: 'voiperrobot',
	},
	{
		id: 'voiperrobot-win-battle',
		difficulty: 'medium',
		title: 'くっつくパンツ',
		condition: 'ボイパーロボットバトルで勝つ',
		category: 'voiperrobot',
	},

	// ricochet-robots

	{
		id: 'ricochet-robots-play',
		difficulty: 'easy',
		title: 'Hey ハイパーロボット',
		condition: 'ハイパーロボットで遊ぶ',
		category: 'ricochet-robots',
	},
	{
		id: 'ricochet-robots-clear',
		difficulty: 'easy',
		title: 'われはロボット',
		condition: 'ハイパーロボットを正解する',
		category: 'ricochet-robots',
	},
	{
		id: 'ricochet-robots-clear-shortest',
		difficulty: 'easy',
		title: 'オートマタ',
		condition: 'ハイパーロボットで最短勝利する',
		category: 'ricochet-robots',
	},
	{
		id: 'ricochet-robots-clear-shortest-over10',
		difficulty: 'medium',
		title: 'アンドロイド',
		condition: 'ハイパーロボットで10手詰め以上の問題で最短勝利する',
		category: 'ricochet-robots',
	},
	{
		id: 'ricochet-robots-clear-shortest-over15',
		difficulty: 'hard',
		title: 'オラクル',
		condition: 'ハイパーロボットで15手詰め以上の問題で最短勝利する',
		category: 'ricochet-robots',
	},
	{
		id: 'ricochet-robots-clear-shortest-over20',
		difficulty: 'professional',
		title: 'デウス・エクス・マキナ',
		condition: 'ハイパーロボットで20手詰め以上の問題で最短勝利する',
		category: 'ricochet-robots',
	},
	{
		id: 'ricochet-robots-buttle-play',
		difficulty: 'easy',
		title: 'ハイパーロボット対戦',
		condition: 'ハイパーロボットバトルで遊ぶ',
		category: 'ricochet-robots',
	},
	{
		id: 'ricochet-robots-buttle-win',
		difficulty: 'easy',
		title: '早見え',
		condition: 'ハイパーロボットバトルで勝利する',
		category: 'ricochet-robots',
	},
	{
		id: 'ricochet-robots-debugger',
		difficulty: 'hard',
		title: 'ﾋﾟｭｰﾝ',
		condition: 'ハイパーロボットのバグを突く',
		category: 'ricochet-robots',
	},
	{
		id: 'ricochet-robots-clear-in-10sec-per-move-over8',
		difficulty: 'medium',
		title: 'ハイパーロボットロボット',
		condition: 'ハイパーロボットで8手詰め以上の問題を、1手あたり10秒以内で最短勝利する',
		category: 'ricochet-robots',
	},
	{
		id: 'ricochet-robots-clear-in-5sec-per-move-over8',
		difficulty: 'hard',
		title: 'スーパーハイパーロボットロボット',
		condition: 'ハイパーロボットで8手詰め以上の問題を、1手あたり5秒以内で最短勝利する',
		category: 'ricochet-robots',
	},
	{
		id: 'ricochet-robots-clear-in-1sec-per-move-over8',
		difficulty: 'professional',
		title: 'ハイパーハイパーロボットロボット',
		condition: 'ハイパーロボットで8手詰め以上の問題を、1手あたり1秒以内で最短勝利する',
		category: 'ricochet-robots',
	},

	// hitandblow

	{
		id: 'hitandblow-play',
		difficulty: 'easy',
		title: '0 Hit 1 Blow',
		condition: 'Hit & Blow で遊ぶ',
		category: 'hitandblow',
	},
	{
		id: 'hitandblow-clear',
		difficulty: 'easy',
		title: '1 Hit 0 Blow',
		condition: 'Hit & Blow をクリアする',
		category: 'hitandblow',
	},
	{
		id: 'hitandblow-clear-6digits-or-more',
		difficulty: 'medium',
		title: '6 Hit 0 Blow',
		condition: 'Hit & Blow をクリアする (6桁以上)',
		category: 'hitandblow',
	},
	{
		id: 'hitandblow-clear-10digits',
		difficulty: 'hard',
		title: '10 Hit 0 Blow',
		condition: 'Hit & Blow をクリアする (10桁)',
		category: 'hitandblow',
	},
	{
		id: 'hitandblow-clear-once-3digits-or-more',
		difficulty: 'professional',
		title: 'guess問が得意',
		condition: 'Hit & Blow を一回のコールでクリアする (3桁以上)',
		category: 'hitandblow',
	},
	{
		id: 'hitandblow-clear-10digits-within-5min',
		difficulty: 'professional',
		title: '実質ソルバ',
		condition: 'Hit & Blow (10桁) を5分以内にクリアする',
		category: 'hitandblow',
	},

	// ahokusa

	{
		id: 'ahokusa-play',
		difficulty: 'easy',
		title: '今話題のゲームがあるんですよ',
		condition: 'あほくさスライドパズルで遊ぶ',
		category: 'ahokusa',
	},
	{
		id: 'ahokusa-clear',
		difficulty: 'easy',
		title: 'まあゆかりさんは天才ですから？',
		condition: 'あほくさスライドパズルをクリアする',
		category: 'ahokusa',
	},
	{
		id: 'ahokusa-clear-shortest',
		difficulty: 'easy',
		title: '敵を華麗にバッタバッタやっつけるわけです',
		condition: 'あほくさスライドパズルを最短でクリアする',
		category: 'ahokusa',
	},
	{
		id: 'ahokusa-clear-once',
		difficulty: 'easy',
		title: 'その結果ランキングに載るわけです！',
		condition: 'あほくさスライドパズルを一発でクリアする',
		category: 'ahokusa',
	},
	{
		id: 'ahokusa-clear-shortest-once',
		difficulty: 'medium',
		title: 'ええんちゃう？',
		condition: 'あほくさスライドパズルを一発かつ最短でクリアする',
		category: 'ahokusa',
	},
	{
		id: 'ahokusa-impossible',
		difficulty: 'easy',
		title: 'わかる（明察）',
		condition: 'あほくさスライドパズルの不成立を指摘する',
		category: 'ahokusa',
	},
	{
		id: 'ahokusa-impossible-once',
		difficulty: 'medium',
		title: 'あ　ほ　く　さ',
		condition: 'あほくさスライドパズルの不成立を一発で指摘する',
		category: 'ahokusa',
	},
	{
		id: 'ahokusa-clear-8s',
		difficulty: 'hard',
		title: '8秒で全員ぶっ飛ばしてやりますよ！！！！！！！',
		condition: 'あほくさスライドパズルを8秒以内にクリアする',
		category: 'ahokusa',
	},
	{
		id: 'ahokusa-impossible-5s',
		difficulty: 'hard',
		title: 'やめたら？このゲーム',
		condition: 'あほくさスライドパズルの不成立を5秒以内に指摘する',
		category: 'ahokusa',
	},
	{
		id: 'ahokusa-sushi-clear-once-89s',
		difficulty: 'professional',
		title: '狂い出しそう-体が震える',
		condition: '寿司スライドパズルを一発かつ89秒以内にクリアする',
		category: 'ahokusa',
	},
	{
		id: 'ahokusa-chiya-clear',
		difficulty: 'hard',
		title: '見習いうらら',
		condition: '千矢スライドパズルをクリアする',
		category: 'ahokusa',
	},
	{
		id: 'ahokusa-chiya-clear-200s',
		difficulty: 'hard',
		title: 'におい占いで！',
		condition: '千矢スライドパズルを200秒以内にクリアする',
		category: 'ahokusa',
	},
	{
		id: 'ahokusa-chiya-impossible-once',
		difficulty: 'hard',
		title: 'おなかが＜・＞＜・＞でてない',
		condition: '千矢スライドパズルの不成立を一発で指摘する',
		category: 'ahokusa',
	},
	{
		id: 'ahokusa-chiya-clear-once-1008s',
		difficulty: 'professional',
		title: '視えた！',
		condition: '千矢スライドパズルを一発で1008秒以内にクリアする',
		category: 'ahokusa',
	},
	{
		id: 'ahokusa-chiya-clear-50s',
		difficulty: 'professional',
		title: '伝説の一番占',
		condition: '千矢スライドパズルを50秒以内にクリアする',
		category: 'ahokusa',
	},

	// atcoder

	{
		id: 'atcoder-participate',
		difficulty: 'medium',
		title: 'はいプロ',
		condition: 'AtCoderのratedな大会に参加する',
		category: 'atcoder',
		counter: 'atcoder-participate',
		value: 1,
	},
	{
		id: 'atcoder-participate-3',
		difficulty: 'medium',
		title: '井井井',
		condition: 'AtCoderのratedな大会に3回参加する',
		category: 'atcoder',
		counter: 'atcoder-participate',
		value: 3,
	},
	{
		id: 'atcoder-participate-5',
		difficulty: 'medium',
		title: '□□□□□',
		condition: 'AtCoderのratedな大会に5回参加する',
		category: 'atcoder',
		counter: 'atcoder-participate',
		value: 5,
	},
	{
		id: 'atcoder-participate-10',
		difficulty: 'hard',
		title: '大事な数なのでZ回書きまLた。',
		condition: 'AtCoderのratedな大会に10回参加する',
		category: 'atcoder',
		counter: 'atcoder-participate',
		value: 10,
	},
	{
		id: 'atcoder-participate-30',
		difficulty: 'professional',
		title: 'AtCoder Crackers',
		condition: 'AtCoderのratedな大会に30回参加する',
		category: 'atcoder',
		counter: 'atcoder-participate',
		value: 30,
	},
	{
		id: 'atcoder-participate-100',
		difficulty: 'professional',
		title: 'AtCoder Express',
		condition: 'AtCoderのratedな大会に100回参加する',
		category: 'atcoder',
		counter: 'atcoder-participate',
		value: 100,
	},
	{
		id: 'atcoder-participate-300',
		difficulty: 'professional',
		title: 'Welcome to AtCoder',
		condition: 'AtCoderのratedな大会に300回参加する',
		category: 'atcoder',
		counter: 'atcoder-participate',
		value: 300,
	},
	{
		id: 'atcoder-rating-plus',
		difficulty: 'medium',
		title: '競プロの天才',
		condition: 'AtCoderでレーティングを上げる',
		category: 'atcoder',
	},
	{
		id: 'atcoder-rating-plus-50',
		difficulty: 'hard',
		title: '競プロ界のtourist',
		condition: 'AtCoderでレーティングを一度に50以上上げる',
		category: 'atcoder',
	},
	{
		id: 'atcoder-rating-plus-minus-zero',
		difficulty: 'hard',
		title: '競プロ界の咲',
		condition: 'AtCoderでレーティングをプラスマイナスゼロで維持する',
		category: 'atcoder',
	},
	{
		id: 'atcoder-rating-minus',
		difficulty: 'medium',
		title: '競プロの終焉を告げる者',
		condition: 'AtCoderでレーティングを下げる',
		category: 'atcoder',
	},
	{
		id: 'atcoder-rating-minus-50',
		difficulty: 'hard',
		title: '実質趣味',
		condition: 'AtCoderでレーティングを一度に50以上下げる',
		category: 'atcoder',
	},
	{
		id: 'atcoder-rating-over-2400',
		difficulty: 'professional',
		title: '競プロするために生まれてきた男',
		condition: 'AtCoderのレーティングを2400以上にする',
		category: 'atcoder',
	},
	{
		id: 'atcoder-all-solve',
		difficulty: 'hard',
		title: 'スペースエクスプローラー高橋君',
		condition: 'AtCoderのratedな (本人がratedでなくてよい) 大会で全ての問題で正の得点を獲得した状態でレーティングを確定させる',
		category: 'atcoder',
	},
	{
		id: 'atcoder-repdigit',
		difficulty: 'hard',
		title: '魔法使い高橋君',
		condition: 'AtCoderでゾロ目の順位 (10進数、3桁以上に限る) でレーティングを確定させる',
		category: 'atcoder',
	},
	{
		id: 'atcoder-prime',
		difficulty: 'medium',
		title: '高橋君と青木君の好きな数',
		condition: 'AtCoderで素数となる順位でレーティングを確定させる',
		category: 'atcoder',
	},
	{
		id: 'atcoder-no-solve',
		difficulty: 'medium',
		title: '器物損壊！高橋君',
		condition: 'AtCoderのレーティング更新対象の大会で1問も解かずにレーティングを確定させる',
		category: 'atcoder',
	},
	{
		id: 'atcoder-fastest-1',
		difficulty: 'medium',
		title: 'ウサギとカメ',
		condition: '10人以上が参加したAtCoderのレーティング更新対象の大会で、最初の問題をatcoderボット登録ユーザーの中で一番早く (ペナルティは考慮しない) 回答する',
		category: 'atcoder',
		counter: 'atcoder-fastest',
		value: 1,
	},
	{
		id: 'atcoder-fastest-5',
		difficulty: 'hard',
		title: '連射王高橋君',
		condition: '10人以上が参加したAtCoderのレーティング更新対象の大会で、最初の問題をatcoderボット登録ユーザーの中で一番早く (ペナルティは考慮しない) 回答する、を5回達成する',
		category: 'atcoder',
		counter: 'atcoder-fastest',
		value: 5,
	},
	{
		id: 'atcoder-fastest-20',
		difficulty: 'professional',
		title: '覚醒ノ高橋君',
		condition: '10人以上が参加したAtCoderのレーティング更新対象の大会で、最初の問題をatcoderボット登録ユーザーの中で一番早く (ペナルティは考慮しない) 回答する、を20回達成する',
		category: 'atcoder',
		counter: 'atcoder-fastest',
		value: 20,
	},
	{
		id: 'atcoder-fastest-100',
		difficulty: 'professional',
		title: '一刀両断',
		condition: '10人以上が参加したAtCoderのレーティング更新対象の大会で、最初の問題をatcoderボット登録ユーザーの中で一番早く (ペナルティは考慮しない) 回答する、を100回達成する',
		category: 'atcoder',
		counter: 'atcoder-fastest',
		value: 100,
	},
	{
		id: 'atcoder-abs-solves-1',
		difficulty: 'easy',
		title: '高橋君の研修',
		condition: 'AtCoder Beginners Selection (practice A を除く) の問題を1問でも解く',
		category: 'atcoder',
		counter: 'atcoder-abs-solves',
		value: 1,
	},
	{
		id: 'atcoder-abs-solves-10',
		difficulty: 'medium',
		title: '全域木',
		condition: 'AtCoder Beginners Selection (practice A を除く) の問題10問を全完する',
		category: 'atcoder',
		counter: 'atcoder-abs-solves',
		value: 10,
	},
	{
		id: 'atcoder-typical-solves-20',
		difficulty: 'medium',
		title: '積み重ね',
		condition: 'AtCoder Beginners Selection (practice A を除く) と競プロ典型90問の問題のうち20問を解く',
		category: 'atcoder',
		counter: 'atcoder-typical-solves',
		value: 20,
	},
	{
		id: 'atcoder-typical-solves-50',
		difficulty: 'hard',
		title: '増築王高橋君',
		condition: 'AtCoder Beginners Selection (practice A を除く) と競プロ典型90問の問題のうち50問を解く',
		category: 'atcoder',
		counter: 'atcoder-typical-solves',
		value: 50,
	},
	{
		id: 'atcoder-typical-solves-100',
		difficulty: 'professional',
		title: 'ほんとうのたたかい',
		condition: 'AtCoder Beginners Selection (practice A を除く) と競プロ典型90問の問題100問を全完する',
		category: 'atcoder',
		counter: 'atcoder-typical-solves',
		value: 100,
	},

	// pwnyaa

	{
		id: 'pwnyaa-tw-half',
		difficulty: 'easy',
		title: 'ポーンではなくパウンですよ!',
		condition: 'pwnable.twで半分以上の問題を解く',
		category: 'pwnyaa',
	},
	{
		id: 'pwnyaa-tw-complete',
		difficulty: 'medium',
		title: 'ぱあんぱいんぱうんぱえんぱおん',
		condition: 'pwnable.twを全完する',
		category: 'pwnyaa',
	},
	{
		id: 'pwnyaa-xyz-half',
		difficulty: 'baby',
		title: '始めることが、大事です',
		condition: 'pwnable.xyzで半分以上の問題を解く',
		category: 'pwnyaa',
	},
	{
		id: 'pwnyaa-xyz-complete',
		difficulty: 'baby',
		title: '続けることが、大事です',
		condition: 'pwnable.xyzを全完する',
		category: 'pwnyaa',
	},
	{
		id: 'pwnyaa-praise-your-birthday',
		difficulty: 'baby',
		title: 'あなたは今、最も難しいことを成し遂げました',
		condition: 'pwnyaaにjoinする',
		category: 'pwnyaa',
	},
	{
		id: 'pwnyaa-ch-half',
		difficulty: 'hard',
		title: '全ての道はpwnに通ず',
		condition: 'cryptohackで半分以上の問題を解く',
		category: 'pwnyaa',
	},
	{
		id: 'pwnyaa-ch-complete',
		difficulty: 'professional',
		title: 'YOU ARE CRYPTO HACKER...',
		condition: 'cryptohackを全完する',
		category: 'pwnyaa',
	},
	{
		id: 'pwnyaa-ksn-half',
		difficulty: 'medium',
		title: 'ニルギリ!',
		condition: 'ksnctfで半分以上の問題を解く',
		category: 'pwnyaa',
	},
	{
		id: 'pwnyaa-ksn-complete',
		difficulty: 'hard',
		title: '村人Aには会えましたか...?',
		condition: 'ksnctfを全完する',
		category: 'pwnyaa',
	},
	{
		id: 'pwnyaa-ah-half',
		difficulty: 'hard',
		title: '_アルパカかわいい！',
		condition: 'AlpacaHackで半分以上の問題を解く',
		category: 'pwnyaa',
	},
	{
		id: 'pwnyaa-ah-complete',
		difficulty: 'professional',
		title: '_しば犬かわいい！',
		condition: 'AlpacaHackを全完する',
		category: 'pwnyaa',
	},
	{
		id: 'pwnyaa-ah-5',
		difficulty: 'easy',
		title: 'アルパカかわいい！',
		condition: 'AlpacaHackで5問以上の問題を解く',
		category: 'pwnyaa',
	},
	{
		id: 'pwnyaa-ah-10',
		difficulty: 'medium',
		title: 'しば犬かわいい！',
		condition: 'AlpacaHackで10問以上の問題を解く',
		category: 'pwnyaa',
	},
	{
		id: 'pwnyaa-ah-20',
		difficulty: 'hard',
		title: '猫かわいい！',
		condition: 'AlpacaHackで20問以上の問題を解く',
		category: 'pwnyaa',
	},
	{
		id: 'pwnyaa-ah-50',
		difficulty: 'professional',
		title: '狼かわいい！',
		condition: 'AlpacaHackを50問以上の問題を解く',
		category: 'pwnyaa',
	},

	// anime

	{
		id: 'anime-answer',
		difficulty: 'easy',
		title: 'アニメ初心者',
		condition: 'アニメ当てクイズで正解する',
		category: 'anime',
		counter: 'anime-answer',
		value: 1,
	},
	{
		id: 'anime-answer-30',
		difficulty: 'hard',
		title: 'アニメ職人',
		condition: 'アニメ当てクイズで30回正解する',
		category: 'anime',
		counter: 'anime-answer',
		value: 30,
	},
	{
		id: 'anime-before-2010',
		difficulty: 'hard',
		title: 'あの頃はよかった',
		condition: 'アニメ当てクイズで2010年より前に放送されたアニメを正解する',
		category: 'anime',
	},
	{
		id: 'anime-before-2000',
		difficulty: 'professional',
		title: 'セル画の香り',
		condition: 'アニメ当てクイズで2000年より前に放送されたアニメを正解する',
		category: 'anime',
	},
	{
		id: 'anime-answer-third-hint',
		difficulty: 'medium',
		title: 'アニメオタク',
		condition: 'アニメ当てクイズでヒント3回以内で正解する',
		category: 'anime',
	},
	{
		id: 'anime-answer-second-hint',
		difficulty: 'medium',
		title: 'アニメ名人',
		condition: 'アニメ当てクイズでヒント2回以内で正解する',
		category: 'anime',
	},
	{
		id: 'anime-answer-first-hint',
		difficulty: 'hard',
		title: 'アニメ達人',
		condition: 'アニメ当てクイズでヒント1回以内で正解する',
		category: 'anime',
		counter: 'anime-answer-first-hint',
		value: 1,
	},
	{
		id: 'anime-answer-first-hint-10',
		difficulty: 'professional',
		title: 'アニメ神',
		condition: 'アニメ当てクイズでヒント1回以内で10回正解する',
		category: 'anime',
		counter: 'anime-answer-first-hint',
		value: 10,
	},
	{
		id: 'anime-answer-first-hint-100',
		difficulty: 'professional',
		title: 'アニメ王',
		condition: 'アニメ当てクイズでヒント1回以内で100回正解する',
		category: 'anime',
		counter: 'anime-answer-first-hint',
		value: 100,
	},
	{
		id: 'anime-extreme-answer-first-hint',
		difficulty: 'professional',
		title: 'モザイクの向こうに',
		condition: 'アニメ当てクイズextremeでヒント1回以内で正解する',
		category: 'anime',
	},
	{
		id: 'anime-song-answer',
		difficulty: 'easy',
		title: 'アニソン初心者',
		condition: 'アニソン当てクイズで正解する',
		category: 'anime',
		counter: 'anime-song-answer',
		value: 1,
	},
	{
		id: 'anime-song-before-2010',
		difficulty: 'hard',
		title: '懐メロハンター',
		condition: 'アニソン当てクイズで2010年より前に放送されたアニメの曲を正解する',
		category: 'anime',
	},
	{
		id: 'anime-song-answer-20',
		difficulty: 'hard',
		title: 'アニソン職人',
		condition: 'アニソン当てクイズで20回正解する',
		category: 'anime',
		counter: 'anime-song-answer',
		value: 20,
	},
	{
		id: 'anime-song-answer-third-hint',
		difficulty: 'medium',
		title: 'アニソンオタク',
		condition: 'アニソン当てクイズでヒント3回以内で正解する',
		category: 'anime',
	},
	{
		id: 'anime-song-answer-second-hint',
		difficulty: 'hard',
		title: 'アニソン名人',
		condition: 'アニソン当てクイズでヒント2回以内で正解する',
		category: 'anime',
	},
	{
		id: 'anime-song-answer-first-hint',
		difficulty: 'hard',
		title: 'アニソン達人',
		condition: 'アニソン当てクイズでヒント1回以内で正解する',
		category: 'anime',
		counter: 'anime-song-answer-first-hint',
		value: 1,
	},
	{
		id: 'anime-song-answer-first-hint-5',
		difficulty: 'professional',
		title: 'アニソン神',
		condition: 'アニソン当てクイズでヒント1回以内で5回正解する',
		category: 'anime',
		counter: 'anime-song-answer-first-hint',
		value: 5,
	},
	{
		id: 'anime-song-answer-first-hint-25',
		difficulty: 'professional',
		title: 'アニソン王',
		condition: 'アニソン当てクイズでヒント1回以内で25回正解する',
		category: 'anime',
		counter: 'anime-song-answer-first-hint',
		value: 25,
	},
	{
		id: 'anime-song-answer-first-hint-125',
		difficulty: 'professional',
		title: 'アニソン中毒',
		condition: 'アニソン当てクイズでヒント1回以内で125回正解する',
		category: 'anime',
		counter: 'anime-song-answer-first-hint',
		value: 125,
	},
	{
		id: 'anime-song-hard-answer',
		difficulty: 'medium',
		title: '学士: アニソン学',
		condition: 'アニソン当てクイズhardで正解する',
		category: 'anime',
	},

	// character-quiz

	{
		id: 'namori-answer',
		difficulty: 'easy',
		title: 'なもり初心者',
		condition: 'なもり当てクイズで正解する',
		category: 'character-quiz',
		counter: 'namori-answer',
		value: 1,
	},
	{
		id: 'namori-answer-20',
		difficulty: 'medium',
		title: 'なもり名人',
		condition: 'なもり当てクイズで20回正解する',
		category: 'character-quiz',
		counter: 'namori-answer',
		value: 20,
	},
	{
		id: 'namori-answer-50',
		difficulty: 'hard',
		title: 'なもり職人',
		condition: 'なもり当てクイズで50回正解する',
		category: 'character-quiz',
		counter: 'namori-answer',
		value: 50,
	},
	{
		id: 'namori-answer-500',
		difficulty: 'professional',
		title: '（：3）三',
		condition: 'なもり当てクイズで500回正解する',
		category: 'character-quiz',
		counter: 'namori-answer',
		value: 500,
	},
	{
		id: 'namori-answer-5000',
		difficulty: 'professional',
		title: '三（ε：）',
		condition: 'なもり当てクイズで5000回正解する',
		category: 'character-quiz',
		counter: 'namori-answer',
		value: 5000,
	},
	{
		id: 'namori-answer-first-hint',
		difficulty: 'hard',
		title: 'なもりの達人',
		condition: 'なもり当てクイズでヒント1回以内で正解する',
		category: 'character-quiz',
		counter: 'namori-answer-first-hint',
		value: 1,
	},
	{
		id: 'namori-answer-first-hint-5', // XXX
		difficulty: 'professional',
		title: 'なもり神',
		condition: 'なもり当てクイズでヒント1回以内で10回正解する',
		category: 'character-quiz',
		counter: 'namori-answer-first-hint',
		value: 10,
	},
	{
		id: 'namori-answer-first-hint-100',
		difficulty: 'professional',
		title: 'なもり王',
		condition: 'なもり当てクイズでヒント1回以内で100回正解する',
		category: 'character-quiz',
		counter: 'namori-answer-first-hint',
		value: 100,
	},
	{
		id: 'namori-answer-first-hint-1000',
		difficulty: 'professional',
		title: 'なもり中毒',
		condition: 'なもり当てクイズでヒント1回以内で1000回正解する',
		category: 'character-quiz',
		counter: 'namori-answer-first-hint',
		value: 1000,
	},

	{
		id: 'ixy-answer',
		difficulty: 'easy',
		title: 'Ixy初心者',
		condition: 'Ixy当てクイズで正解する',
		category: 'character-quiz',
		counter: 'ixy-answer',
		value: 1,
	},
	{
		id: 'ixy-answer-20',
		difficulty: 'medium',
		title: 'Ixy名人',
		condition: 'Ixy当てクイズで20回正解する',
		category: 'character-quiz',
		counter: 'ixy-answer',
		value: 20,
	},
	{
		id: 'ixy-answer-50',
		difficulty: 'hard',
		title: 'Ixy職人',
		condition: 'Ixy当てクイズで50回正解する',
		category: 'character-quiz',
		counter: 'ixy-answer',
		value: 50,
	},
	{
		id: 'ixy-answer-500',
		difficulty: 'professional',
		title: 'Ｉｘｙ',
		condition: 'Ixy当てクイズで500回正解する',
		category: 'character-quiz',
		counter: 'ixy-answer',
		value: 500,
	},
	{
		id: 'ixy-answer-first-hint',
		difficulty: 'hard',
		title: 'Ixyの達人',
		condition: 'Ixy当てクイズでヒント1回以内で正解する',
		category: 'character-quiz',
		counter: 'ixy-answer-first-hint',
		value: 1,
	},
	{
		id: 'ixy-answer-first-hint-5',
		difficulty: 'professional',
		title: 'Ixy神',
		condition: 'Ixy当てクイズでヒント1回以内で10回正解する',
		category: 'character-quiz',
		counter: 'ixy-answer-first-hint',
		value: 10,
	},

	// kirafan

	{
		id: 'kirafan-answer',
		difficulty: 'easy',
		title: 'かけだし召喚士',
		condition: 'きらファン当てクイズで正解する',
		category: 'kirafan',
		counter: 'kirafan-answer',
		value: 1,
	},
	{
		id: 'kirafankirafan-answer-20',
		difficulty: 'medium',
		title: '一人前の召喚士',
		condition: 'きらファン当てクイズで20回正解する',
		category: 'kirafan',
		counter: 'kirafan-answer',
		value: 20,
	},
	{
		id: 'kirafankirafan-answer-50',
		difficulty: 'hard',
		title: 'ベテラン召喚士',
		condition: 'きらファン当てクイズで50回正解する',
		category: 'kirafan',
		counter: 'kirafan-answer',
		value: 50,
	},
	{
		id: 'kirafan-answer-500',
		difficulty: 'professional',
		title: 'ランプのおすみつき',
		condition: 'きらファン当てクイズで500回正解する',
		category: 'kirafan',
		counter: 'kirafan-answer',
		value: 500,
	},
	{
		id: 'kirafan-answer-5000',
		difficulty: 'professional',
		title: 'すくすく育った召喚士',
		condition: 'きらファン当てクイズで5000回正解する',
		category: 'kirafan',
		counter: 'kirafan-answer',
		value: 5000,
	},
	{
		id: 'kirafan-answer-first-hint',
		difficulty: 'hard',
		title: '聖典マニア',
		condition: 'きらファン当てクイズでヒント1回以内で正解する',
		category: 'kirafan',
		counter: 'kirafan-answer-first-hint',
		value: 1,
	},
	{
		id: 'kirafan-answer-first-hint-5', // XXX
		difficulty: 'professional',
		title: '女神候補生',
		condition: 'きらファン当てクイズでヒント1回以内で10回正解する',
		category: 'kirafan',
		counter: 'kirafan-answer-first-hint',
		value: 10,
	},
	{
		id: 'kirafan-answer-first-hint-100',
		difficulty: 'professional',
		title: 'きららさんといっしょ',
		condition: 'きらファン当てクイズでヒント1回以内で100回正解する',
		category: 'kirafan',
		counter: 'kirafan-answer-first-hint',
		value: 100,
	},
	{
		id: 'kirafan-answer-first-hint-1000',
		difficulty: 'professional',
		title: '新たなる聖典の紡ぎ手',
		condition: 'きらファン当てクイズでヒント1回以内で1000回正解する',
		category: 'kirafan',
		counter: 'kirafan-answer-first-hint',
		value: 1000,
	},
	{
		id: 'kirafan-easy-answer',
		difficulty: 'easy',
		title: '見知らぬ少女',
		condition: 'きらファン当てクイズeasyで正解する',
		category: 'kirafan',
		counter: 'kirafan-easy-answer',
		value: 1,
	},
	{
		id: 'kirafan-easy-answer-20',
		difficulty: 'medium',
		title: '立ち上がった少女',
		condition: 'きらファン当てクイズeasyで20回正解する',
		category: 'kirafan',
		counter: 'kirafan-easy-answer',
		value: 20,
	},
	{
		id: 'kirafan-easy-answer-50',
		difficulty: 'hard',
		title: '踏み出した少女',
		condition: 'きらファン当てクイズeasyで50回正解する',
		category: 'kirafan',
		counter: 'kirafan-easy-answer',
		value: 50,
	},
	{
		id: 'kirafan-easy-answer-500',
		difficulty: 'professional',
		title: 'かけだし絵描き',
		condition: 'きらファン当てクイズeasyで500回正解する',
		category: 'kirafan',
		counter: 'kirafan-easy-answer',
		value: 500,
	},
	{
		id: 'kirafan-easy-answer-first-hint',
		difficulty: 'hard',
		title: '元女神候補生',
		condition: 'きらファン当てクイズeasyでヒント1回以内で正解する',
		category: 'kirafan',
		counter: 'kirafan-easy-answer-first-hint',
		value: 1,
	},
	{
		id: 'kirafan-easy-answer-first-hint-10',
		difficulty: 'professional',
		title: '聖典の広め手',
		condition: 'きらファン当てクイズeasyでヒント1回以内で10回正解する',
		category: 'kirafan',
		counter: 'kirafan-easy-answer-first-hint',
		value: 10,
	},
	{
		id: 'kirafan-easy-answer-first-hint-100',
		difficulty: 'professional',
		title: 'スクライブギルド長',
		condition: 'きらファン当てクイズeasyでヒント1回以内で100回正解する',
		category: 'kirafan',
		counter: 'kirafan-easy-answer-first-hint',
		value: 100,
	},

	// bungo-quiz
	{
		id: 'bungo-answer',
		difficulty: 'easy',
		title: '読書初心者',
		condition: '文豪/文豪当てクイズで正解する',
		category: 'bungo-quiz',
		counter: 'bungo-answer',
		value: 1,
	},
	{
		id: 'bungo-answer-20',
		difficulty: 'medium',
		title: '読書名人',
		condition: '文豪/文豪当てクイズで20回正解する',
		category: 'bungo-quiz',
		counter: 'bungo-answer',
		value: 20,
	},
	{
		id: 'bungo-answer-50',
		difficulty: 'hard',
		title: '趣味は読書です',
		condition: '文豪/文豪当てクイズで50回正解する',
		category: 'bungo-quiz',
		counter: 'bungo-answer',
		value: 50,
	},
	{
		id: 'bungo-answer-500',
		difficulty: 'professional',
		title: '歩く図書館',
		condition: '文豪/文豪当てクイズで500回正解する',
		category: 'bungo-quiz',
		counter: 'bungo-answer',
		value: 500,
	},
	{
		id: 'bungo-answer-first-hint',
		difficulty: 'hard',
		title: 'Google Scholar',
		condition: '文豪/文豪当てクイズでヒント1回以内で正解する',
		category: 'bungo-quiz',
	},

	// crossword

	{
		id: 'crossword-cells-1',
		difficulty: 'easy',
		title: '一頭地を抜く',
		condition: 'crosswordで累計1マス以上のマスを開く',
		category: 'crossword',
		counter: 'crossword-cells',
		value: 1,
	},
	{
		id: 'crossword-cells-20',
		difficulty: 'medium',
		title: 'クロスワード・マニア',
		condition: 'crosswordで累計20マス以上のマスを開く',
		category: 'crossword',
		counter: 'crossword-cells',
		value: 20,
	},
	{
		id: 'crossword-cells-100',
		difficulty: 'hard',
		title: '100マス計算',
		condition: 'crosswordで累計100マス以上のマスを開く',
		category: 'crossword',
		counter: 'crossword-cells',
		value: 100,
	},
	{
		id: 'crossword-cells-1000',
		difficulty: 'professional',
		title: '千枚通し',
		condition: 'crosswordで累計1000マス以上のマスを開く',
		category: 'crossword',
		counter: 'crossword-cells',
		value: 1000,
	},
	{
		id: 'crossword-cells-10000',
		difficulty: 'professional',
		title: '10000マス計算',
		condition: 'crosswordで累計10000マス以上のマスを開く',
		category: 'crossword',
		counter: 'crossword-cells',
		value: 10000,
	},
	{
		id: 'crossword-wins-1',
		difficulty: 'medium',
		title: 'クロスワード・初勝利',
		condition: 'crosswordで1マス以上のマスを開け、盤面をクリアする',
		category: 'crossword',
		counter: 'crossword-wins',
		value: 1,
	},
	{
		id: 'crossword-wins-3',
		difficulty: 'medium',
		title: 'クロスワード・ハットトリック',
		condition: 'crosswordで1マス以上のマスを開け、盤面を3回クリアする',
		category: 'crossword',
		counter: 'crossword-wins',
		value: 3,
	},
	{
		id: 'crossword-wins-21',
		difficulty: 'hard',
		title: 'クロスワード・ゲームセット',
		condition: 'crosswordで1マス以上のマスを開け、盤面を21回クリアする',
		category: 'crossword',
		counter: 'crossword-wins',
		value: 21,
	},
	{
		id: 'crossword-wins-150',
		difficulty: 'professional',
		title: 'クロスワード・勝利の女神',
		condition: 'crosswordで1マス以上のマスを開け、盤面を150回クリアする',
		category: 'crossword',
		counter: 'crossword-wins',
		value: 150,
	},
	{
		id: 'crossword-wins-1000',
		difficulty: 'professional',
		title: 'クロスワード・プロフェッショナル',
		condition: 'crosswordで1マス以上のマスを開け、盤面を1000回クリアする',
		category: 'crossword',
		counter: 'crossword-wins',
		value: 1000,
	},
	{
		id: 'crossword-wins-1000',
		difficulty: 'professional',
		title: 'サザンクロス',
		condition: 'crosswordで1マス以上のマスを開け、盤面を1000回クリアする',
		category: 'crossword',
		counter: 'crossword-wins',
		value: 1000,
	},
	{
		id: 'crossword-solo',
		difficulty: 'hard',
		title: 'クロスワード・完投勝利',
		condition: 'crosswordで1人で全てのマスを開いてクリアする',
		category: 'crossword',
	},
	{
		id: 'crossword-clear',
		difficulty: 'medium',
		title: 'クロスワード・決勝点',
		condition: 'crosswordでクリアを決定する最後の単語を回答する',
		category: 'crossword',
	},
	{
		id: 'crossword-closer',
		difficulty: 'hard',
		title: 'クロスワード・クローザー',
		condition: 'crosswordでクリアを決定する最後の単語を回答する。ただしそのゲームにおいてそれ以外に回答を行ってはいけない (正解・不正解を問わない)',
		category: 'crossword',
	},
	{
		id: 'crossword-buzzer-beater',
		difficulty: 'hard',
		title: 'クロスワード・ブザービーター',
		condition: 'crosswordで制限時間が切れる2秒以内に、クリアを決定する最後の単語を回答する',
		category: 'crossword',
	},
	{
		id: 'crossword-game-time-le-quarter',
		difficulty: 'hard',
		title: 'クロスワード・ゲームセッター',
		condition: 'crosswordで制限時間の1/4以下の時間でクリアしたゲームにおいて、1マス以上のマスを開ける',
		category: 'crossword',
	},
	{
		id: 'crossword-misses-ge-20',
		difficulty: 'medium',
		title: 'クロスワード・フリースインガー',
		condition: 'crosswordでクリアしたゲームにおいて、20個以上の誤答を行い、一度も正解しない',
		category: 'crossword',
	},
	{
		id: 'crossword-contributors-ge-11',
		difficulty: 'professional',
		title: 'クロスワード・オールスターゲーム',
		condition: 'crosswordで1ゲームに11人以上が正答した状態でクリアしたゲームにおいて、1マス以上のマスを開ける',
		category: 'crossword',
	},
	{
		id: 'grossword-wins-1',
		difficulty: 'hard',
		title: 'シングル・グロス',
		condition: 'grosswordで1マス以上のマスを開け、盤面をクリアする',
		category: 'crossword',
		counter: 'grossword-wins',
		value: 1,
	},
	{
		id: 'grossword-wins-12',
		difficulty: 'hard',
		title: 'ダズン・グロス',
		condition: 'grosswordで1マス以上のマスを開け、盤面を12回クリアする',
		category: 'crossword',
		counter: 'grossword-wins',
		value: 12,
	},
	{
		id: 'grossword-wins-144',
		difficulty: 'professional',
		title: 'グロス・グロス',
		condition: 'grosswordで1マス以上のマスを開け、盤面を144回クリアする',
		category: 'crossword',
		counter: 'grossword-wins',
		value: 144,
	},
	{
		id: 'grossword-wins-1728',
		difficulty: 'professional',
		title: 'グレート・グロス・グロス',
		condition: 'grosswordで1マス以上のマスを開け、盤面を1728回クリアする',
		category: 'crossword',
		counter: 'grossword-wins',
		value: 1728,
	},

	// denim (bcr)
	{
		id: 'bcr-denim-fullsplit',
		difficulty: 'medium',
		title: 'ガチ割れ行くぜ！',
		condition: '白鍵を4567鍵に寄せ、デニム譜面を割る',
		category: 'bcr',
	},
	{
		id: 'bcr-denim-reversplit',
		difficulty: 'medium',
		title: '逆割れ行くぜ！',
		condition: '白鍵を1234鍵に寄せ、デニム譜面を2P割れにする',
		category: 'bcr',
	},

	// achievement-quiz
	{
		id: 'achievement-quiz-clear',
		difficulty: 'easy',
		title: '実績初心者',
		condition: '実績当てクイズで正解する',
		category: 'achievement-quiz',
		counter: 'achievement-quiz-clear',
		value: 1,
	},
	{
		id: 'achievement-quiz-clear-20',
		difficulty: 'hard',
		title: '実績職人',
		condition: '実績当てクイズで20回正解する',
		category: 'achievement-quiz',
		counter: 'achievement-quiz-clear',
		value: 20,
	},
	{
		id: 'achievement-quiz-clear-baby',
		difficulty: 'medium',
		title: 'BE MY BABY', // BE MY BABY
		condition: '実績当てクイズで難易度babyの実績の名前を当てる',
		category: 'achievement-quiz',
		counter: 'achievement-quiz-clear-baby',
		value: 1,
	},
	{
		id: 'achievement-quiz-clear-easy',
		difficulty: 'medium',
		title: 'Used to be 諦めるのは easy', // Can We Go Back
		condition: '実績当てクイズで難易度easyの実績の名前を当てる',
		category: 'achievement-quiz',
		counter: 'achievement-quiz-clear-easy',
		value: 1,
	},
	{
		id: 'achievement-quiz-clear-medium',
		difficulty: 'medium',
		title: 'TORO is Medium toro', // Oh! SUSHI （スシ食いねェ!）
		condition: '実績当てクイズで難易度mediumの実績の名前を当てる',
		category: 'achievement-quiz',
		counter: 'achievement-quiz-clear-medium',
		value: 1,
	},
	{
		id: 'achievement-quiz-clear-hard',
		difficulty: 'hard',
		title: 'はーどっこい！', // はやくそれになりたい！
		condition: '実績当てクイズで難易度hardの実績の名前を当てる',
		category: 'achievement-quiz',
		counter: 'achievement-quiz-clear-hard',
		value: 1,
	},
	{
		id: 'achievement-quiz-clear-professional',
		difficulty: 'hard',
		title: '神業を超えたプロの螺旋', // SUSHI食べたい
		condition: '実績当てクイズで難易度professionalの実績の名前を当てる',
		category: 'achievement-quiz',
		counter: 'achievement-quiz-clear-professional',
		value: 1,
	},
	{
		id: 'achievement-quiz-clear-this-achievement',
		difficulty: 'professional',
		title: 'マッチポンプ',
		condition: '実績当てクイズでこの実績の名前を当てる',
		category: 'achievement-quiz',
	},

	// sorting-riddles
	{
		id: 'sorting-riddles-answer',
		difficulty: 'easy',
		title: 'すぞぞでななるソトー正解',
		condition: 'ソートなぞなぞで正解する',
		category: 'sorting-riddles',
		counter: 'sorting-riddles-answer',
		value: 1,
	},
	{
		id: 'sorting-riddles-answer-20',
		difficulty: 'hard',
		title: '02すぞぞでななるソトー回正解',
		condition: 'ソートなぞなぞで20回正解する',
		category: 'sorting-riddles',
		counter: 'sorting-riddles-answer',
		value: 20,
	},
	{
		id: 'sorting-riddles-4-or-more-characters',
		difficulty: 'easy',
		title: '4すぞぞででななるソトー上以字文正解',
		condition: 'ソートなぞなぞで4文字以上で正解する',
		category: 'sorting-riddles',
	},
	{
		id: 'sorting-riddles-7-or-more-characters',
		difficulty: 'hard',
		title: '7すぞぞででななるソトー上以字文正解',
		condition: 'ソートなぞなぞで7文字以上で正解する',
		category: 'sorting-riddles',
	},
	{
		id: 'sorting-riddles-10-or-more-characters',
		difficulty: 'professional',
		title: '01すぞぞででななるソトー上以字文正解',
		condition: 'ソートなぞなぞで10文字以上で正解する',
		category: 'sorting-riddles',
	},

	// hangman
	{
		id: 'hangman-letters-1',
		difficulty: 'easy',
		title: 'Guess what?',
		condition: 'Hangmanで1文字のguessを成功させる',
		category: 'hangman',
		counter: 'hangman-letters',
		value: 1,
	},
	{
		id: 'hangman-letters-26',
		difficulty: 'medium',
		title: 'The whole alphabet',
		condition: 'Hangmanで累計26文字以上のguessを成功させる',
		category: 'hangman',
		counter: 'hangman-letters',
		value: 26,
	},
	{
		id: 'hangman-letters-100',
		difficulty: 'hard',
		title: 'Centuple of letters',
		condition: 'Hangmanで累計100文字以上のguessを成功させる',
		category: 'hangman',
		counter: 'hangman-letters',
		value: 100,
	},
	{
		id: 'hangman-letters-1000',
		difficulty: 'professional',
		title: 'Serious dedication?',
		condition: 'Hangmanで累計1000文字以上のguessを成功させる',
		category: 'hangman',
		counter: 'hangman-letters',
		value: 1000,
	},
	{
		id: 'hangman-letters-10000',
		difficulty: 'professional',
		title: 'Myriacharacter',
		condition: 'Hangmanで累計10000文字以上のguessを成功させる',
		category: 'hangman',
		counter: 'hangman-letters',
		value: 10000,
	},
	{
		id: 'hangman-consecutive-10',
		difficulty: 'hard',
		title: 'Hangman prodigy',
		condition: 'Hangmanで連続10回ゲームをクリアする (hard以上限定)',
		category: 'hangman',
		counter: 'hangman-consecutive',
		value: 10,
	},
	{
		id: 'hangman-consecutive-15',
		difficulty: 'professional',
		title: 'Hangman millionaire',
		condition: 'Hangmanで連続15回ゲームをクリアする (hard以上限定)',
		category: 'hangman',
		counter: 'hangman-consecutive',
		value: 15,
	},
	{
		id: 'hangman-consecutive-20',
		difficulty: 'professional',
		title: 'Hangking',
		condition: 'Hangmanで連続20回ゲームをクリアする (hard以上限定)',
		category: 'hangman',
		counter: 'hangman-consecutive',
		value: 20,
	},
	{
		id: 'hangman-clear-1',
		difficulty: 'medium',
		title: 'One good deed a day',
		condition: 'Hangmanでゲームを1回クリアする',
		category: 'hangman',
		counter: 'hangman-clear',
		value: 1,
	},
	{
		id: 'hangman-clear-20',
		difficulty: 'hard',
		title: 'Vocab hero',
		condition: 'Hangmanでゲームを累計20回クリアする',
		category: 'hangman',
		counter: 'hangman-clear',
		value: 20,
	},
	{
		id: 'hangman-clear-100',
		difficulty: 'professional',
		title: 'Countless lives saved',
		condition: 'Hangmanでゲームを累計100回クリアする',
		category: 'hangman',
		counter: 'hangman-clear',
		value: 100,
	},
	{
		id: 'hangman-clear-500',
		difficulty: 'professional',
		title: 'Good hangman makes a good crop',
		condition: 'Hangmanでゲームを累計500回クリアする',
		category: 'hangman',
		counter: 'hangman-clear',
		value: 500,
	},
	{
		id: 'hangman-perfect',
		difficulty: 'hard',
		title: 'Hangman without the Hang',
		condition: 'Hangmanで一度もguessを失敗させずにゲームクリアをする',
		category: 'hangman',
	},
	{
		id: 'hangman-reverse-perfect',
		difficulty: 'easy',
		title: 'The perfect executioner',
		condition: 'Hangmanで一度もguessを成功させずにゲームオーバーする',
		category: 'hangman',
	},
	{
		id: 'hangman-short',
		difficulty: 'hard',
		title: 'Not easy being short',
		condition: 'Hangmanで6文字以下の単語でゲームクリアする',
		category: 'hangman',
	},
	{
		id: 'hangman-xzjq',
		difficulty: 'medium',
		title: 'The unwanted letters',
		condition: 'HangmanでX, Z, J, Qのいずれかを含む単語でゲームクリアする',
		category: 'hangman',
	},
	{
		id: 'hangman-extreme-clear',
		difficulty: 'medium',
		title: 'An arduous undertaking',
		condition: 'Hangmanでextreme難易度をゲームクリアする',
		category: 'hangman',
	},
	{
		id: 'hangman-multiple-letters',
		difficulty: 'hard',
		title: 'Word wizard',
		condition: 'Hangmanで3種類以上の文字を同時に言い当てる',
		category: 'hangman',
	},
	{
		id: 'hangman-cleared-with-hangman',
		difficulty: 'hard',
		title: 'Dream Luck Activated',
		condition: 'Hangmanを単語"hangman"でゲームクリアする',
		category: 'hangman',
	},

	// octas
	{
		id: 'octas-beginner',
		difficulty: 'easy',
		title: 'octasプレーヤー',
		condition: 'octasをプレーする',
		category: 'octas',
	},
	{
		id: 'octas-win-1',
		difficulty: 'medium',
		title: '初ゴール',
		condition: 'octasで他人に勝利する',
		category: 'octas',
		counter: 'octas-win',
		value: 1,
	},
	{
		id: 'octas-win-5',
		difficulty: 'medium',
		title: 'octasエキスパート',
		condition: 'octasで他人に5回勝利する',
		category: 'octas',
		counter: 'octas-win',
		value: 5,
	},
	{
		id: 'octas-owngoaler',
		difficulty: 'easy',
		title: 'オウンゴール',
		condition: 'octasで自分から自陣のゴールに入れる',
		category: 'octas',
	},
	{
		id: 'octas-catch',
		difficulty: 'hard',
		title: '袋の鼠',
		condition: 'octasで相手を手詰まりで負かす',
		category: 'octas',
	},

	// wordle-battle
	{
		id: 'wordle-battle-win-1',
		difficulty: 'medium',
		title: 'Wordle勝利',
		condition: 'Wordle Battle で相手の単語を当て、勝利する',
		category: 'wordle-battle',
		counter: 'wordle-battle-win',
		value: 1,
	},
	{
		id: 'wordle-battle-win-5',
		difficulty: 'hard',
		title: 'Wordleオタク',
		condition: 'Wordle Battle で 5 回相手の単語を当て、勝利する',
		category: 'wordle-battle',
		counter: 'wordle-battle-win',
		value: 5,
	},
	{
		id: 'wordle-battle-win-25',
		difficulty: 'professional',
		title: 'Wordleオタク2',
		condition: 'Wordle Battle で 25 回相手の単語を当て、勝利する',
		category: 'wordle-battle',
		counter: 'wordle-battle-win',
		value: 25,
	},
	{
		id: 'wordle-battle-short',
		difficulty: 'medium',
		title: 'Wordle Bat(またはBa)',
		condition: 'Wordle Battle で相手の 3 文字以下の単語を当て、勝利する',
		category: 'wordle-battle',
	},
	{
		id: 'wordle-battle-long',
		difficulty: 'hard',
		title: 'Wordle Battle with overly prolonged expressions and phrases',
		condition: 'Wordle Battle で相手の 13 文字以上の単語を当て、勝利する',
		category: 'wordle-battle',
	},
	{
		id: 'wordle-battle-letters-16',
		difficulty: 'medium',
		title: '緑と黄色の正方形',
		condition: 'Wordle Battle で緑または黄色の四角を16個集める',
		category: 'wordle-battle',
		counter: 'wordle-battle-letters',
		value: 16,
	},
	{
		id: 'wordle-battle-letters-64',
		difficulty: 'hard',
		title: '緑と黄色の立方体',
		condition: 'Wordle Battle で緑または黄色の四角を64個集める',
		category: 'wordle-battle',
		counter: 'wordle-battle-letters',
		value: 64,
	},
	{
		id: 'wordle-battle-letters-256',
		difficulty: 'professional',
		title: '緑と黄色の正八胞体',
		condition: 'Wordle Battle で緑または黄色の四角を256個集める',
		category: 'wordle-battle',
		counter: 'wordle-battle-letters',
		value: 256,
	},
	{
		id: 'wordle-battle-letters-1024',
		difficulty: 'professional',
		title: '緑と黄色の五次元超立方体',
		condition: 'Wordle Battle で緑または黄色の四角を1024個集める',
		category: 'wordle-battle',
		counter: 'wordle-battle-letters',
		value: 1024,
	},
	{
		id: 'wordle-battle-long-rally',
		difficulty: 'hard',
		title: 'Wordle粘り勝ち',
		condition: 'Wordle Battle で 15 個以上のクエリを投げ、勝利をする',
		category: 'wordle-battle',
	},

	// discord

	{
		id: 'discord-hayaoshi-correct-1',
		difficulty: 'easy',
		title: 'クイズ初心者',
		condition: 'Discordの早押しクイズで正解する',
		counter: 'discord-hayaoshi-correct',
		value: 1,
		category: 'discord',
	},
	{
		id: 'discord-hayaoshi-correct-10',
		difficulty: 'medium',
		title: 'クイズ中級者',
		condition: 'Discordの早押しクイズで10回正解する',
		counter: 'discord-hayaoshi-correct',
		value: 10,
		category: 'discord',
	},
	{
		id: 'discord-hayaoshi-correct-100',
		difficulty: 'hard',
		title: 'クイズ上級者',
		condition: 'Discordの早押しクイズで100回正解する',
		counter: 'discord-hayaoshi-correct',
		value: 100,
		category: 'discord',
	},
	{
		id: 'discord-hayaoshi-correct-1000',
		difficulty: 'professional',
		title: 'クイズ王',
		condition: 'Discordの早押しクイズで1000回正解する',
		counter: 'discord-hayaoshi-correct',
		value: 1000,
		category: 'discord',
	},
	{
		id: 'discord-hayaoshi-correct-10000',
		difficulty: 'professional',
		title: 'クイズ中毒',
		condition: 'Discordの早押しクイズで10000回正解する',
		counter: 'discord-hayaoshi-correct',
		value: 10000,
		category: 'discord',
	},
	{
		id: 'discord-hayaoshi-my-quiz-is-used',
		difficulty: 'hard',
		title: 'この問題見たことある',
		condition: 'Discordの早押しクイズで自分が作問した問題が出題される',
		counter: 'discord-hayaoshi-my-quiz-is-used',
		value: 1,
		category: 'discord',
	},
	{
		id: 'discord-hayaoshi-my-quiz-is-used-50',
		difficulty: 'hard',
		title: '作問の鬼',
		condition: 'Discordの早押しクイズで自分が作問した問題が50問出題される',
		counter: 'discord-hayaoshi-my-quiz-is-used',
		value: 50,
		category: 'discord',
	},
	{
		id: 'discord-hayaoshi-my-quiz-is-used-300',
		difficulty: 'professional',
		title: '作問の天才',
		condition: 'Discordの早押しクイズで自分が作問した問題が300問出題される',
		counter: 'discord-hayaoshi-my-quiz-is-used',
		value: 300,
		category: 'discord',
	},
	{
		id: 'discord-hayaoshi-my-quiz-is-used-2000',
		difficulty: 'professional',
		title: '作問中毒',
		condition: 'Discordの早押しクイズで自分が作問した問題が2000問出題される',
		counter: 'discord-hayaoshi-my-quiz-is-used',
		value: 2000,
		category: 'discord',
	},
	{
		id: 'discord-hayaoshi-win-1',
		difficulty: 'medium',
		title: '火を神/',
		condition: 'Discordの早押しクイズ大会で優勝する',
		counter: 'discord-hayaoshi-win',
		value: 1,
		category: 'discord',
	},
	{
		id: 'discord-hayaoshi-win-10',
		difficulty: 'hard',
		title: 'なぜ山/',
		condition: 'Discordの早押しクイズ大会で10回優勝する',
		counter: 'discord-hayaoshi-win',
		value: 10,
		category: 'discord',
	},
	{
		id: 'discord-hayaoshi-win-100',
		difficulty: 'professional',
		title: 'おい/',
		condition: 'Discordの早押しクイズ大会で100回優勝する',
		counter: 'discord-hayaoshi-win',
		value: 100,
		category: 'discord',
	},
	{
		id: 'discord-hayaoshi-win-1000',
		difficulty: 'professional',
		title: '4以上/',
		condition: 'Discordの早押しatcoder-fastest-20クイズ大会で1000回優勝する',
		counter: 'discord-hayaoshi-win',
		value: 1000,
		category: 'discord',
	},
	{
		id: 'discord-hayaoshi-time-lt2',
		difficulty: 'hard',
		title: 'アップ、/',
		condition: 'Discordの早押しクイズで解答時間2秒以内で正解する',
		category: 'discord',
	},

	// remember-english

	{
		id: 'remember-english-challenge-1',
		difficulty: 'easy',
		title: 'Learn by Heart',
		condition: 'rememberbotに回答する',
		counter: 'remember-english-challenge',
		value: 1,
		category: 'remember-english',
	},
	{
		id: 'remember-english-challenge-10',
		difficulty: 'medium',
		title: 'Recollection',
		condition: 'rememberbotに10回回答する',
		counter: 'remember-english-challenge',
		value: 10,
		category: 'remember-english',
	},
	{
		id: 'remember-english-challenge-100',
		difficulty: 'hard',
		title: 'Random Access Memory',
		condition: 'rememberbotに100回回答する',
		counter: 'remember-english-challenge',
		value: 100,
		category: 'remember-english',
	},
	{
		id: 'remember-english-challenge-500',
		difficulty: 'professional',
		title: 'Mnemosyne',
		condition: 'rememberbotに500回回答する',
		counter: 'remember-english-challenge',
		value: 500,
		category: 'remember-english',
	},
	{
		id: 'remember-english-add-word-1',
		difficulty: 'easy',
		title: 'Single-minded',
		condition: 'rememberbotに単語を登録する',
		counter: 'remember-english-add-word',
		value: 1,
		category: 'remember-english',
	},
	{
		id: 'remember-english-add-word-5',
		difficulty: 'medium',
		title: 'Little Flashcard',
		condition: 'rememberbotに単語を5個登録する',
		counter: 'remember-english-add-word',
		value: 5,
		category: 'remember-english',
	},
	{
		id: 'remember-english-add-word-50',
		difficulty: 'hard',
		title: 'Large Vocabulary',
		condition: 'rememberbotに単語を50個登録する',
		counter: 'remember-english-add-word',
		value: 50,
		category: 'remember-english',
	},
	{
		id: 'remember-english-add-word-200',
		difficulty: 'professional',
		title: 'Gross Glossary',
		condition: 'rememberbotに単語を200個登録する',
		counter: 'remember-english-add-word',
		value: 200,
		category: 'remember-english',
	},
	{
		id: 'remember-english-challenge-first-30',
		difficulty: 'hard',
		title: 'Early Bird',
		condition: 'rememberbotに他の誰よりも早く30回回答する',
		counter: 'remember-english-challenge-first',
		value: 30,
		category: 'remember-english',
	},
	{
		id: 'remember-english-challenge-first-100',
		difficulty: 'professional',
		title: 'Happy as a Lark',
		condition: 'rememberbotに他の誰よりも早く100回回答する',
		counter: 'remember-english-challenge-first',
		value: 100,
		category: 'remember-english',
	},

	// golfbot

	{
		id: 'golfbot-participate',
		difficulty: 'medium',
		title: 'カップイン',
		condition: 'golfbotのコンテストに参加してACする',
		category: 'golfbot',
		counter: 'golfbot-participate',
		value: 1,
	},
	{
		id: 'golfbot-participate-10',
		difficulty: 'hard',
		title: '常連ゴルファー',
		condition: 'golfbotのコンテストに10回参加してACする',
		category: 'golfbot',
		counter: 'golfbot-participate',
		value: 10,
	},
	{
		id: 'golfbot-host',
		difficulty: 'hard',
		title: 'ゴルフやろうぜ！',
		condition: 'golfbotのコンテストを主催する',
		category: 'golfbot',
		counter: 'golfbot-host',
		value: 1,
	},
	{
		id: 'golfbot-host-10',
		difficulty: 'professional',
		title: '日本ゴルフ協会',
		condition: 'golfbotのコンテストを10回主催する',
		category: 'golfbot',
		counter: 'golfbot-host',
		value: 10,
	},

	// topic

	{
		id: 'topic-adopted-1',
		difficulty: 'easy',
		title: '話題の近傍',
		condition: 'Slackでの発言がtopicに採用される',
		category: 'topic',
		counter: 'topic-adopted',
		value: 1,
	},
	{
		id: 'topic-adopted-10',
		difficulty: 'medium',
		title: '話題の中心',
		condition: 'Slackでの発言がtopicに10回採用される',
		category: 'topic',
		counter: 'topic-adopted',
		value: 10,
	},
	{
		id: 'topic-adopted-100',
		difficulty: 'hard',
		title: '話題の天元',
		condition: 'Slackでの発言がtopicに100回採用される',
		category: 'topic',
		counter: 'topic-adopted',
		value: 100,
	},
	{
		id: 'topic-adopted-500',
		difficulty: 'professional',
		title: '話題の有頂天',
		condition: 'Slackでの発言がtopicに500回採用される',
		category: 'topic',
		counter: 'topic-adopted',
		value: 500,
	},

	// slowquiz

	{
		id: 'slowquiz-correct-answer-1',
		difficulty: 'medium',
		title: '雌伏雄飛',
		condition: '1日1文字クイズに正解する',
		category: 'slowquiz',
		counter: 'slowquiz-correct-answer',
		value: 1,
	},
	{
		id: 'slowquiz-correct-answer-10',
		difficulty: 'hard',
		title: '面壁九年',
		condition: '1日1文字クイズに10回正解する',
		category: 'slowquiz',
		counter: 'slowquiz-correct-answer',
		value: 10,
	},
	{
		id: 'slowquiz-correct-answer-100',
		difficulty: 'professional',
		title: '按兵不動',
		condition: '1日1文字クイズに100回正解する',
		category: 'slowquiz',
		counter: 'slowquiz-correct-answer',
		value: 100,
	},
	{
		id: 'slowquiz-first-correct-answer-1',
		difficulty: 'hard',
		title: '機を見るに敏',
		condition: '1日1文字クイズに誰よりも早く正解する',
		category: 'slowquiz',
		counter: 'slowquiz-first-correct-answer',
		value: 1,
	},
	{
		id: 'slowquiz-first-correct-answer-30',
		difficulty: 'professional',
		title: '神速',
		condition: '1日1文字クイズに誰よりも早く30回正解する',
		category: 'slowquiz',
		counter: 'slowquiz-first-correct-answer',
		value: 30,
	},
	{
		id: 'slowquiz-first-correct-answer-100',
		difficulty: 'professional',
		title: '電光石火',
		condition: '1日1文字クイズに誰よりも早く100回正解する',
		category: 'slowquiz',
		counter: 'slowquiz-first-correct-answer',
		value: 100,
	},
	{
		id: 'slowquiz-correct-answer-first-letter-1',
		difficulty: 'hard',
		title: '巧遅は拙速に如かず',
		condition: '1日1文字クイズで1日目に正解する',
		category: 'slowquiz',
		counter: 'slowquiz-correct-answer-first-letter',
		value: 1,
	},
	{
		id: 'slowquiz-correct-answer-first-letter-10',
		difficulty: 'professional',
		title: '疾風迅雷',
		condition: '1日1文字クイズで1日目に10回正解する',
		category: 'slowquiz',
		counter: 'slowquiz-correct-answer-first-letter',
		value: 10,
	},
	{
		id: 'slowquiz-normal-correct-answer-first-letter-1',
		difficulty: 'professional',
		title: '究極の早押し',
		condition: '1日1文字クイズのジャンル【正統派】の問題で1日目に正解する',
		category: 'slowquiz',
		counter: 'slowquiz-normal-correct-answer-first-letter',
		value: 1,
	},
	{
		id: 'slowquiz-normal-correct-answer-first-letter-10',
		difficulty: 'professional',
		title: '韋駄天',
		condition: '1日1文字クイズのジャンル【正統派】の問題で1日目に10回正解する',
		category: 'slowquiz',
		counter: 'slowquiz-normal-correct-answer-first-letter',
		value: 10,
	},
	{
		id: 'slowquiz-correct-answer-le-third-letter-1',
		difficulty: 'medium',
		title: '巧遅',
		condition: '1日1文字クイズで3日以内に正解する',
		category: 'slowquiz',
		counter: 'slowquiz-correct-answer-le-third-letter',
		value: 1,
	},
	{
		id: 'slowquiz-wrong-answer-100',
		difficulty: 'hard',
		title: '失敗は成功のもと',
		condition: '1日1文字クイズに100回誤答する',
		category: 'slowquiz',
		counter: 'slowquiz-wrong-answer',
		value: 100,
	},
	{
		id: 'slowquiz-wrong-answer-1000',
		difficulty: 'professional',
		title: '牛の歩みも千里',
		condition: '1日1文字クイズに1000回誤答する',
		category: 'slowquiz',
		counter: 'slowquiz-wrong-answer',
		value: 1000,
	},
	{
		id: 'slowquiz-register-quiz-1',
		difficulty: 'easy',
		title: 'スーパー作問者',
		condition: '1日1文字クイズに問題を登録する',
		category: 'slowquiz',
		counter: 'slowquiz-register-quiz',
		value: 1,
	},
	{
		id: 'slowquiz-complete-quiz-1',
		difficulty: 'professional',
		title: '完走した感想ですが',
		condition: '1日1文字クイズで作問した問題が、1人以上に正解された状態で完走する',
		category: 'slowquiz',
		counter: 'slowquiz-complete-quiz',
		value: 1,
	},
	{
		id: 'slowquiz-correct-answer-by-bot-1',
		difficulty: 'hard',
		title: 'フランケンシュタイン症候群',
		condition: '1日1文字クイズがBOTに正解される',
		category: 'slowquiz',
		counter: 'slowquiz-correct-answer-by-bot',
		value: 1,
	},
	{
		id: 'slowquiz-first-correct-answer-by-bot-1',
		difficulty: 'professional',
		title: 'R.U.R.',
		condition: '1日1文字クイズがBOTに最初に正解される',
		category: 'slowquiz',
		counter: 'slowquiz-first-correct-answer-by-bot',
		value: 1,
	},

	// taimai

	{
		id: 'taimai-correct-answer-1',
		difficulty: 'easy',
		title: '太郎さんはウミガメにひき肉のバジル炒めをかけようとした。なぜ?',
		condition: 'タイマイで正解する',
		category: 'taimai',
		counter: 'taimai-correct-answer',
		value: 1,
	},
	{
		id: 'taimai-correct-answer-10',
		difficulty: 'medium',
		title: '花子さんは贅沢な買い物の自慢をしたら怒られた。なぜ?',
		condition: 'タイマイで10回正解する',
		category: 'taimai',
		counter: 'taimai-correct-answer',
		value: 10,
	},
	{
		id: 'taimai-correct-answer-100',
		difficulty: 'hard',
		title: '医療用麻薬が解禁された結果、カメは怯えた。なぜ?',
		condition: 'タイマイで100回正解する',
		category: 'taimai',
		counter: 'taimai-correct-answer',
		value: 100,
	},
	{
		id: 'taimai-contribute-quiz-1',
		difficulty: 'easy',
		title: '女は意味不明な文章を見て喜んだ。なぜ?',
		condition: 'タイマイで寄稿する',
		category: 'taimai',
		counter: 'taimai-contribute-quiz',
		value: 1,
	},
	{
		id: 'taimai-contribute-quiz-10',
		difficulty: 'medium',
		title: '女は誰よりもその分野の識者であるにも関わらず、少ししか理解できないと語る。なぜ?',
		condition: 'タイマイで10回寄稿する',
		category: 'taimai',
		counter: 'taimai-contribute-quiz',
		value: 10,
	},
	{
		id: 'taimai-contribute-quiz-100',
		difficulty: 'hard',
		title: '男は、研究をしなければならないのにゲームに明け暮れていた。なぜ?',
		condition: 'タイマイで100回寄稿する',
		category: 'taimai',
		counter: 'taimai-contribute-quiz',
		value: 100,
	},
	{
		id: 'taimai-ask-30',
		difficulty: 'easy',
		title: '男は一度進み始めると壁に当たるまで止まれないという。なぜ?',
		condition: 'タイマイで30回質問をする',
		category: 'taimai',
		counter: 'taimai-ask',
		value: 30,
	},
	{
		id: 'taimai-ask-100',
		difficulty: 'medium',
		title: '自分の心の中に思っていたことがある日突然街中に大々的に掲示された。なぜ?',
		condition: 'タイマイで100回質問をする',
		category: 'taimai',
		counter: 'taimai-ask',
		value: 100,
	},
	{
		id: 'taimai-ask-300',
		difficulty: 'hard',
		title: 'ある男は脅威となる人に積極的に会いに行くという。なぜ?',
		condition: 'タイマイで300回質問をする',
		category: 'taimai',
		counter: 'taimai-ask',
		value: 300,
	},
	{
		id: 'taimai-0q-1',
		difficulty: 'professional',
		title: 'あるサークルではあまりにも自明な問題で水平思考クイズをしている。なぜ?',
		condition: 'タイマイで誰も質問をしないうちに正解する',
		category: 'taimai',
		counter: 'taimai-0q',
		value: 1,
	},
	{
		id: 'taimai-lt3q-1',
		difficulty: 'hard',
		title: 'ある女は市外局番をひたすら覚えているという。なぜ?',
		condition: 'タイマイで質問3回以内で正解する',
		category: 'taimai',
		counter: 'taimai-lt3q',
		value: 1,
	},
	{
		id: 'taimai-gt25q-1',
		difficulty: 'medium',
		title: 'あるオタクは些細な言葉遣いの違いをひたすら指摘している。なぜ?',
		condition: 'タイマイで25回質問があった問題に正解する',
		category: 'taimai',
		counter: 'taimai-gt25q',
		value: 1,
	},

	// map-guessr

	{
		id: 'coord-quiz-easy-answer-1',
		difficulty: 'easy',
		title: '新天地',
		condition: '座標当てクイズで1回正解する',
		category: 'map-guessr',
		counter: 'coord-quiz-easy-answer',
		value: 1,
	},
	{
		id: 'coord-quiz-easy-answer-10',
		difficulty: 'medium',
		title: '出張',
		condition: '座標当てクイズで10回正解する',
		category: 'map-guessr',
		counter: 'coord-quiz-easy-answer',
		value: 10,
	},
	{
		id: 'coord-quiz-easy-answer-100',
		difficulty: 'hard',
		title: '旅行好き',
		condition: '座標当てクイズで100回正解する',
		category: 'map-guessr',
		counter: 'coord-quiz-easy-answer',
		value: 100,
	},
	{
		id: 'coord-quiz-easy-answer-1000',
		difficulty: 'professional',
		title: 'バックパッカー',
		condition: '座標当てクイズで1000回正解する',
		category: 'map-guessr',
		counter: 'coord-quiz-easy-answer',
		value: 1000,
	},
	{
		id: 'coord-quiz-medium-answer-1',
		difficulty: 'easy',
		title: '地図オタク',
		condition: '500km以下座標当てクイズで1回正解する',
		category: 'map-guessr',
		counter: 'coord-quiz-medium-answer',
		value: 1,
	},
	{
		id: 'coord-quiz-medium-answer-10',
		difficulty: 'medium',
		title: '国土地理院',
		condition: '500km以下座標当てクイズで10回正解する',
		category: 'map-guessr',
		counter: 'coord-quiz-medium-answer',
		value: 10,
	},
	{
		id: 'coord-quiz-medium-answer-100',
		difficulty: 'hard',
		title: '伊能忠敬',
		condition: '500km以下座標当てクイズで100回正解する',
		category: 'map-guessr',
		counter: 'coord-quiz-medium-answer',
		value: 100,
	},
	{
		id: 'coord-quiz-medium-answer-1000',
		difficulty: 'professional',
		title: '人工衛星',
		condition: '500km以下座標当てクイズで1000回正解する',
		category: 'map-guessr',
		counter: 'coord-quiz-medium-answer',
		value: 1000,
	},
	{
		id: 'coord-quiz-hard-answer-1',
		difficulty: 'medium',
		title: '100kmを行く者は90kmを半ばとす',
		condition: '100km以下座標当てクイズで1回正解する',
		category: 'map-guessr',
		counter: 'coord-quiz-hard-answer',
		value: 1,
	},
	{
		id: 'coord-quiz-hard-answer-10',
		difficulty: 'hard',
		title: '可愛い子には旅をさせよ',
		condition: '100km以下座標当てクイズで10回正解する',
		category: 'map-guessr',
		counter: 'coord-quiz-hard-answer',
		value: 10,
	},
	{
		id: 'coord-quiz-hard-answer-100',
		difficulty: 'hard',
		title: '旅することは生きること',
		condition: '100km以下座標当てクイズで100回正解する',
		category: 'map-guessr',
		counter: 'coord-quiz-hard-answer',
		value: 100,
	},
	{
		id: 'coord-quiz-hard-answer-1000',
		difficulty: 'professional',
		title: '他国を見れば見るほど、私はいよいよ私の祖国を愛する',
		condition: '100km以下座標当てクイズで1000回正解する',
		category: 'map-guessr',
		counter: 'coord-quiz-hard-answer',
		value: 1000,
	},
	{
		id: 'coord-quiz-professional-answer-1',
		difficulty: 'medium',
		title: '空飛ぶ絨毯',
		condition: '20km以下座標当てクイズで1回正解する',
		category: 'map-guessr',
		counter: 'coord-quiz-professional-answer',
		value: 1,
	},
	{
		id: 'coord-quiz-professional-answer-10',
		difficulty: 'hard',
		title: 'TSGerの不思議な冒険',
		condition: '20km以下座標当てクイズで10回正解する',
		category: 'map-guessr',
		counter: 'coord-quiz-professional-answer',
		value: 10,
	},
	{
		id: 'coord-quiz-professional-answer-100',
		difficulty: 'hard',
		title: '上空二万フィート',
		condition: '20km以下座標当てクイズで100回正解する',
		category: 'map-guessr',
		counter: 'coord-quiz-professional-answer',
		value: 100,
	},
	{
		id: 'coord-quiz-professional-answer-1000',
		difficulty: 'professional',
		title: '地球は青かった',
		condition: '20km以下座標当てクイズで1000回正解する',
		category: 'map-guessr',
		counter: 'coord-quiz-professional-answer',
		value: 1000,
	},
	{
		id: 'coord-quiz-30sec-answer-1',
		difficulty: 'easy',
		title: '飛ぶ鳥を落とす勢い',
		condition: '座標当てクイズで30秒以内に正解する',
		category: 'map-guessr',
		counter: 'coord-quiz-30sec-answer',
		value: 1,
	},

	// qrcode-quiz

	{
		id: 'qrcode-quiz-answer-1',
		difficulty: 'easy',
		title: 'ようこそQRコードの世界へ',
		condition: 'QR当てクイズのmaskedモードで正解する',
		category: 'qrcode-quiz',
		counter: 'qrcode-quiz-answer',
		value: 1,
	},
	{
		id: 'qrcode-quiz-answer-10',
		difficulty: 'medium',
		title: 'バーじゃないコード',
		condition: 'QR当てクイズのmaskedモードで10回正解する',
		category: 'qrcode-quiz',
		counter: 'qrcode-quiz-answer',
		value: 10,
	},
	{
		id: 'qrcode-quiz-answer-100',
		difficulty: 'hard',
		title: 'もうスマホはいらない',
		condition: 'QR当てクイズのmaskedモードで100回正解する',
		category: 'qrcode-quiz',
		counter: 'qrcode-quiz-answer',
		value: 100,
	},
	{
		id: 'qrcode-quiz-answer-1000',
		difficulty: 'professional',
		title: 'デンソー',
		condition: 'QR当てクイズのmaskedモードで1000回正解する',
		category: 'qrcode-quiz',
		counter: 'qrcode-quiz-answer',
		value: 1000,
	},
	{
		id: 'qrcode-quiz-answer-less-than-10s-1',
		difficulty: 'professional',
		title: 'クイックレスポンス',
		condition: 'QR当てクイズのmaskedモードで10秒以内に正解する',
		category: 'qrcode-quiz',
		counter: 'qrcode-quiz-answer-less-than-10s',
		value: 1,
	},
	{
		id: 'qrcode-quiz-answer-less-than-45s-1',
		difficulty: 'hard',
		title: '算数ドリルは終わりません！',
		condition: 'QR当てクイズのmaskedモードで45秒以内に正解する',
		category: 'qrcode-quiz',
		counter: 'qrcode-quiz-answer-less-than-45s',
		value: 1,
	},
	{
		id: 'qrcode-quiz-answer-less-than-150s-1',
		difficulty: 'medium',
		title: 'QRの早見え',
		condition: 'QR当てクイズのmaskedモードで150秒以内に正解する',
		category: 'qrcode-quiz',
		counter: 'qrcode-quiz-answer-less-than-150s',
		value: 1,
	},

	// oneiromancy

	{
		id: 'oneiromancy-analyzed-1',
		difficulty: 'easy',
		title: '窓付き',
		condition: '夢占いBOTで夢を占われる',
		category: 'oneiromancy',
		counter: 'oneiromancy-analyzed',
		value: 1,
	},
	{
		id: 'oneiromancy-analyzed-5',
		difficulty: 'medium',
		title: 'トロイメライ',
		condition: '夢占いBOTで夢を5回占われる',
		category: 'oneiromancy',
		counter: 'oneiromancy-analyzed',
		value: 5,
	},
	{
		id: 'oneiromancy-analyzed-30',
		difficulty: 'hard',
		title: 'ルシッドドリーム',
		condition: '夢占いBOTで夢を30回占われる',
		category: 'oneiromancy',
		counter: 'oneiromancy-analyzed',
		value: 30,
	},
	{
		id: 'oneiromancy-analyzed-100',
		difficulty: 'professional',
		title: '夢のまた夢',
		condition: '夢占いBOTで夢を100回占われる',
		category: 'oneiromancy',
		counter: 'oneiromancy-analyzed',
		value: 100,
	},
	{
		id: 'oneiromancy-analyze-5',
		difficulty: 'easy',
		title: 'コンステレーション',
		condition: '夢占いBOTで夢を5回占う',
		category: 'oneiromancy',
		counter: 'oneiromancy-analyze',
		value: 5,
	},
	{
		id: 'oneiromancy-analyze-30',
		difficulty: 'medium',
		title: '八卦八段',
		condition: '夢占いBOTで夢を30回占う',
		category: 'oneiromancy',
		counter: 'oneiromancy-analyze',
		value: 30,
	},
	{
		id: 'oneiromancy-scores-5000',
		difficulty: 'hard',
		title: 'カセクシス',
		condition: '夢占いBOTで占われた今日の運勢の合計が5000点になる',
		category: 'oneiromancy',
		counter: 'oneiromancy-scores',
		value: 5000,
	},
	{
		id: 'oneiromancy-score-below-20-1',
		difficulty: 'hard',
		title: 'イルマの注射',
		condition: '夢占いBOTで今日の運勢が20点以下になる',
		category: 'oneiromancy',
		counter: 'oneiromancy-score-below-20',
		value: 1,
	},
	{
		id: 'oneiromancy-score-above-80-1',
		difficulty: 'hard',
		title: 'ウサギの穴の冒険',
		condition: '夢占いBOTで今日の運勢が80点以上になる',
		category: 'oneiromancy',
		counter: 'oneiromancy-score-above-80',
		value: 1,
	},
	{
		id: 'oneiromancy-score-over-100-1',
		difficulty: 'professional',
		title: '華胥の国に遊ぶ',
		condition: '夢占いBOTで今日の運勢が100点を超える',
		category: 'oneiromancy',
		counter: 'oneiromancy-score-over-100',
		value: 1,
	},
	{
		id: 'oneiromancy-score-under-0-1',
		difficulty: 'professional',
		title: '邯鄲の夢',
		condition: '夢占いBOTで今日の運勢が0点未満になる',
		category: 'oneiromancy',
		counter: 'oneiromancy-score-under-0',
		value: 1,
	},
	{
		id: 'oneiromancy-newyear-analyzed-1',
		difficulty: 'medium',
		title: '一年の計',
		condition: '夢占いBOTに初夢を占われる',
		category: 'oneiromancy',
		counter: 'oneiromancy-newyear-analyzed',
		value: 1,
	},

	// city-symbol

	{
		id: 'city-symbol-answer-1',
		difficulty: 'easy',
		title: '模範的村人',
		condition: '市章当てクイズで正解する',
		category: 'city-symbol',
		counter: 'city-symbol-answer',
		value: 1,
	},
	{
		id: 'city-symbol-answer-10',
		difficulty: 'medium',
		title: '模範的町民',
		condition: '市章当てクイズで10回正解する',
		category: 'city-symbol',
		counter: 'city-symbol-answer',
		value: 10,
	},
	{
		id: 'city-symbol-answer-100',
		difficulty: 'hard',
		title: '模範的区民',
		condition: '市章当てクイズで100回正解する',
		category: 'city-symbol',
		counter: 'city-symbol-answer',
		value: 100,
	},
	{
		id: 'city-symbol-answer-1000',
		difficulty: 'professional',
		title: '模範的市民',
		condition: '市章当てクイズで1000回正解する',
		category: 'city-symbol',
		counter: 'city-symbol-answer',
		value: 1000,
	},
	{
		id: 'city-symbol-answer-hakatashi-1',
		difficulty: 'professional',
		title: '博多市民',
		condition: '市章当てクイズで博多市を正解する',
		category: 'city-symbol',
		counter: 'city-symbol-answer-hakatashi',
		value: 1,
	},

	// nmpz

	{
		id: 'nmpz-country-1',
		difficulty: 'easy',
		title: 'Guessing where I am on Google Maps',
		condition: 'NMPZで国を1回正解する',
		category: 'nmpz',
		counter: 'nmpz-country-answer',
		value: 1,
	},
	{
		id: 'nmpz-country-100',
		difficulty: 'hard',
		title: 'Nice.',
		condition: 'NMPZで国を100回正解する',
		category: 'nmpz',
		counter: 'nmpz-country-answer',
		value: 100,
	},
	{
		id: 'nmpz-country-1000',
		difficulty: 'professional',
		title: 'Next.',
		condition: 'NMPZで国を1000回正解する',
		category: 'nmpz',
		counter: 'nmpz-country-answer',
		value: 1000,
	},
	{
		id: 'nmpz-country-no-hint',
		difficulty: 'hard',
		title: 'But I can see no hints',
		condition: 'NMPZでヒントなしで国を正解する',
		category: 'nmpz',
		counter: 'nmpz-country-no-hint-answer',
		value: 1,
	},
	{
		id: 'nmpz-country-thailand',
		difficulty: 'hard',
		title: 'No, this is Thailand.',
		condition: 'NMPZでタイを正解する',
		category: 'nmpz',
		counter: 'nmpz-country-thailand-answer',
		value: 1,
	},

	// autogen-quiz
	{
		id: 'autogen-quiz-answer-1',
		difficulty: 'easy',
		title: 'ジョージ・マロリー',
		condition: '自動生成クイズで正解する',
		category: 'autogen-quiz',
		counter: 'autogen-quiz-answer',
		value: 1,
	},
	{
		id: 'autogen-quiz-answer-10',
		difficulty: 'medium',
		title: 'タンブルウィード',
		condition: '自動生成クイズで10回正解する',
		category: 'autogen-quiz',
		counter: 'autogen-quiz-answer',
		value: 10,
	},
	{
		id: 'autogen-quiz-answer-100',
		difficulty: 'hard',
		title: 'エクレア',
		condition: '自動生成クイズで100回正解する',
		category: 'autogen-quiz',
		counter: 'autogen-quiz-answer',
		value: 100,
	},
	{
		id: 'autogen-quiz-answer-1000',
		difficulty: 'professional',
		title: 'アリストテレスの提灯',
		condition: '自動生成クイズで1000回正解する',
		category: 'autogen-quiz',
		counter: 'autogen-quiz-answer',
		value: 1000,
	},
	{
		id: 'autogen-quiz-answer-main-answer-tsg-1',
		difficulty: 'hard',
		title: 'TSGが正しい',
		condition: '自動生成クイズで「TSG」が正答の問題を正解する (別解は不可)',
		category: 'autogen-quiz',
		counter: 'autogen-quiz-answer-main-answer-tsg',
		value: 1,
	},
	{
		id: 'autogen-quiz-answer-main-answer-chatgpt-1',
		difficulty: 'hard',
		title: 'AIのお膳立て',
		condition: '自動生成クイズで「ChatGPT」が正答の問題を正解する (別解は不可)',
		category: 'autogen-quiz',
		counter: 'autogen-quiz-answer-main-answer-chatgpt',
		value: 1,
	},
	{
		id: 'autogen-quiz-answer-main-answer-クイズ-1',
		difficulty: 'hard',
		title: 'クイズのクイズ',
		condition: '自動生成クイズで「クイズ」が正答の問題を正解する (別解は不可)',
		category: 'autogen-quiz',
		counter: 'autogen-quiz-answer-main-answer-クイズ',
		value: 1,
	},
	{
		id: 'autogen-quiz-answer-main-answer-コロンビア-1',
		difficulty: 'hard',
		title: '中央アメリカのパナマと陸上で国境を接している南アメリカの国',
		condition: '自動生成クイズで「コロンビア」が正答の問題を正解する (別解は不可)',
		category: 'autogen-quiz',
		counter: 'autogen-quiz-answer-main-answer-コロンビア',
		value: 1,
	},
	{
		id: 'autogen-quiz-answer-main-answer-self-name-1',
		difficulty: 'hard',
		title: '自分を答える',
		condition: '自動生成クイズでSlackでの自分の名前が正答の問題を正解する (別解は不可)',
		category: 'autogen-quiz',
		counter: 'autogen-quiz-answer-main-answer-self-name',
		value: 1,
	},

	// achievements

	{
		id: 'achievements',
		difficulty: 'easy',
		title: '実績解除',
		condition: '初めて実績解除する',
		category: 'achievements',
	},
	{
		id: 'achievements-3',
		difficulty: 'easy',
		title: '解解解除',
		condition: '難易度easy以上の実績を3つ解除する',
		category: 'achievements',
	},
	{
		id: 'achievements-10',
		difficulty: 'medium',
		title: '解解解解解解解解解解除',
		condition: '難易度easy以上の実績を10個解除する',
		category: 'achievements',
	},
	{
		id: 'achievements-70',
		difficulty: 'hard',
		title: '実績七十古来稀なり',
		condition: '難易度easy以上の実績を70個解除する',
		category: 'achievements',
	},
	{
		id: 'achievements-master',
		difficulty: 'hard',
		title: '実績マスター',
		condition: '難易度medium以上の実績を10個解除する',
		category: 'achievements',
	},

	// manual

	{
		id: 'sig',
		difficulty: 'easy',
		title: 'TSG初心者',
		condition: '分科会に参加する',
		category: 'manual',
		manual: true,
	},
	{
		id: 'sig-3times',
		difficulty: 'medium',
		title: 'TSG中級者',
		condition: '分科会に3回以上参加する',
		category: 'manual',
		manual: true,
	},
	{
		id: 'sig-5times',
		difficulty: 'hard',
		title: 'TSG上級者',
		condition: '分科会に5回以上参加する',
		category: 'manual',
		manual: true,
	},
	{
		id: 'create-sig',
		difficulty: 'medium',
		title: 'はじめてのオフ会主催',
		condition: '分科会を開催・運営する',
		category: 'manual',
		manual: true,
	},
	{
		id: 'create-sig-3times',
		difficulty: 'hard',
		title: '人気TSGer',
		condition: '分科会を3回以上開催・運営する',
		category: 'manual',
		manual: true,
	},
	{
		id: 'create-sig-5times',
		difficulty: 'professional',
		title: '大物TSGer',
		condition: '分科会を5回以上開催・運営する',
		category: 'manual',
		manual: true,
	},
	{
		id: 'no-one-came-to-sig',
		difficulty: 'professional',
		title: '参加者は誰一人来ませんでした',
		condition: '自身が開催した分科会の参加者が0人になった回に遭遇する',
		category: 'manual',
		manual: true,
	},
	{
		id: 'clubroom',
		difficulty: 'medium',
		title: '足跡',
		condition: 'TSGの部室を訪問する',
		category: 'manual',
		manual: true,
	},
	{
		id: 'heiankyo-alien',
		difficulty: 'hard',
		title: '歴史との邂逅',
		condition: 'TSGの部室で平安京エイリアンをプレイする',
		category: 'manual',
		manual: true,
	},
	{
		id: 'scrapbox',
		difficulty: 'medium',
		title: '切り抜き箱',
		condition: 'scrapboxに自分の名前の記事を作成する',
		category: 'manual',
		manual: true,
	},
	{
		id: 'github',
		difficulty: 'hard',
		title: 'コントリビューター',
		condition: 'GitHubのtsg-ut下のリポジトリにコミットする',
		category: 'manual',
		manual: true,
	},
	{
		id: 'github-slackbot',
		difficulty: 'hard',
		title: 'BOT駆動開発',
		condition: 'GitHubのtsg-ut/slackbotにコミットする',
		category: 'manual',
		manual: true,
	},
	{
		id: 'github-review',
		difficulty: 'hard',
		title: 'レビュアー',
		condition: 'GitHubのtsg-ut下のリポジトリでのPRにレビューをする',
		category: 'manual',
		manual: true,
	},
	{
		id: 'hakatashi-typo',
		difficulty: 'medium',
		title: 'urusee',
		condition: 'sandboxでhakatashiのtypoを一番目に指摘し、:urusee:で反応される',
		category: 'manual',
		manual: true,
	},
	{
		id: 'a-tour-of-go-completion',
		difficulty: 'medium',
		title: 'satosを巡る冒険',
		condition: 'A Tour of Go のすべてのチャプターを修了する',
		category: 'manual',
		manual: true,
	},
];

const achievementMap = new Map(achievements.map((achievement) => [achievement.id, achievement]));

export default achievementMap;
