"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.set = exports.get = exports.increment = exports.unlock = void 0;
const unlock = () => { };
exports.unlock = unlock;
const increment = () => { };
exports.increment = increment;
const get = () => { };
exports.get = get;
const set = () => { };
exports.set = set;
