services:
  slackbot:
    build: slackbot
    volumes:
      - ..:/code
    stdin_open: true
    tty: true
    command: npm run dev -- --only better-custom-response
    environment:
      - TEAM_ID=${TEAM_ID}
      - SIGNING_SECRET=${SIGNING_SECRET}
      - SLACK_TOKEN=${SLACK_TOKEN}
      - HAKATASHI_TOKEN=${HAKATASHI_TOKEN}
      - CHANNEL_SANDBOX=${CHANNEL_SANDBOX}
      - SLACK_VERIFICATION_TOKEN=${SLACK_VERIFICATION_TOKEN}

  tunnel:
    build:
      context: tunnel
      dockerfile: Dockerfile
      args:
        - HTTP_PROXY_TOKEN=${HTTP_PROXY_TOKEN}
    stdin_open: true
    tty: true
    command: node index.mjs --remote wss://slackbot-api.tsg.ne.jp/wsfwd --host slackbot
