name: Create and publish a Codespaces Docker image

on:
  push:
    branches:
      - master

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (slackbot)
        id: push_slackbot
        uses: docker/build-push-action@v6
        with:
          context: .devcontainer/slackbot
          push: true
          tags: ghcr.io/tsg-ut/slackbot-codespaces-image-slackbot:${{ env.BRANCH_NAME }}
          build-args: |
            BRANCH_NAME=${{ env.BRANCH_NAME }}

      - name: Generate artifact attestation (slackbot)
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/tsg-ut/slackbot-codespaces-image-slackbot
          subject-digest: ${{ steps.push_slackbot.outputs.digest }}
          push-to-registry: true
