name: Test

on:
  - push
  - pull_request

jobs:
  test-js:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Tools
        uses: asdf-vm/actions/install@v3
        with:
          # https://github.com/asdf-vm/actions/issues/587
          asdf_branch: v0.15.0

      - name: Before Install
        run: |
          mkdir -p shogi/boards
          touch shogi/boards/temp.sqlite3

      - run: npm ci

      - name: Typecheck files not covered by tests
        run: npx tsgo --noEmit
        env:
          NODE_OPTIONS: --max-old-space-size=8192

      - name: Test
        run: npm run test:coverage
        env:
          NODE_OPTIONS: --trace-warnings --trace-deprecation --trace-exit --trace-uncaught --unhandled-rejections=strict --max-old-space-size=8192

      - name: codecov
        continue-on-error: true
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  test-rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Tools
        uses: asdf-vm/actions/install@v3
        with:
          # https://github.com/asdf-vm/actions/issues/587
          asdf_branch: v0.15.0

      - name: build
        run: cargo build --all --verbose

      - name: test
        run: cargo test --all --verbose
